Repository hrzntal/horizon, pull requests merged in 2021-06, with the labels that each got.

#220 ESS Crow and common docking ports
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/shuttles/exploration_crow.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/common_docks.dm
  code/modules/shuttle/exploration.dm
  tgstation.dme
Labels: Area:Mapping, Status:Test Merged

#228 Updates readme, actions, labels in actions [ci skip]
  .github/workflows/conflicts.yml
  .github/workflows/stale.yml
  README.md
Labels: Area:Repository

#230 Digitigrade GAGS jumpsuits + sneakers, cargo tech icon state fix
  code/datums/greyscale/greyscale_configs.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/security.dm
  icons/horizon/mob/clothing/mutant/under/uniform_digi.dmi
  icons/horizon/mob/clothing/mutant/uniform_digi.dmi
  icons/mob/clothing/feet_gags_digi.dmi
  icons/mob/clothing/under/color_gags_digi.dmi
Labels: Area:Sprites

#213 Ports and modernizes Trading system from Nebula/Bay
  code/__DEFINES/trading.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/trading.dm
  code/modules/trading/__TRADING_HELPERS.dm
  code/modules/trading/_bought_goods.dm
  code/modules/trading/_sold_goods.dm
  code/modules/trading/_trade_hub.dm
  code/modules/trading/_trader.dm
  code/modules/trading/bought_goods/goods.dm
  code/modules/trading/sold_goods/food.dm
  code/modules/trading/sold_goods/goods.dm
  code/modules/trading/sold_goods/weaponry.dm
  code/modules/trading/trade_hub_overmap.dm
  code/modules/trading/trade_machines.dm
  code/modules/trading/traders/food.dm
  code/modules/trading/traders/goods.dm
  code/modules/trading/traders/weaponry.dm
  tgstation.dme
Labels: Status:Test Merged

#236 Lower title music volume to 30%
  code/game/sound.dm
Labels: Type:Quality of Life

#233 Shield Generators + Overmap Hazards + Overmap tweaks
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
  _maps/shuttles/exploration_crow.dmm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/overmap.dm
  code/game/shuttle_engines.dm
  code/modules/meteors/meteors.dm
  code/modules/overmap/_OVERMAP_HELPERS.dm
  code/modules/overmap/overmap_hazards.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_shuttle_shields.dm
  code/modules/overmap/overmap_visuals.dm
  code/modules/overmap/propulsion_engine.dm
  code/modules/overmap/shield_generator.dm
  code/modules/overmap/shuttle_control_component.dm
  code/modules/overmap/shuttle_extension.dm
  code/modules/overmap/sun_system.dm
  code/modules/shuttle/shuttle.dm
  icons/obj/machines/shield_gen.dmi
  icons/overmap/overmap.dmi
  tgstation.dme
Labels: Area:Mapping, Area:Sprites

#237 Grammar fix on map info
  code/datums/map_config.dm
Labels: Area:Grammar and Formatting

#238 Adds overmap "loot" and Transporters to collect it
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/trading.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/overmap/overmap_lock.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_shuttle_process.dm
  code/modules/overmap/overmap_shuttle_transporter.dm
  code/modules/overmap/overmap_transportable.dm
  code/modules/overmap/propulsion_engine.dm
  code/modules/overmap/shuttle_extension.dm
  code/modules/overmap/sun_system.dm
  code/modules/overmap/transporter.dm
  code/modules/trading/trade_hub_overmap.dm
  icons/obj/machines/transporter.dmi
  icons/overmap/overmap.dmi
  tgstation.dme
Labels: Area:Mapping, Area:Sprites, Status:Merge Conflict

#240 Overmap projectiles and overmap mining update
  code/__DEFINES/overmap.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/overmap/mining_laser.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/overmap_ore_rock.dm
  code/modules/overmap/overmap_projectile.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_shuttle_process.dm
  code/modules/overmap/shuttle_extension.dm
  code/modules/overmap/sun_system.dm
  icons/obj/machines/mining_laser.dmi
  icons/overmap/overmap.dmi
  icons/overmap/overmap_projectiles.dmi
  icons/overmap/targeted.dmi
  tgstation.dme
Labels: Area:Sprites, Type:Feature

#89 Re-enable specific species emotes and some emotecode TLC
  hrzn/modules/emotes/code/dna_screams.dm
  hrzn/modules/emotes/code/emotes.dm
Labels: Area:Sounds, Status:Test Merged, Type:Fix

#241 Planetary backend: Modular weather controllers and modular atmospheres
  _maps/RandomRuins/IceRuins/icemoon_underground_lavaland.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_library.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_wendigo_cave.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_swarmer_crash.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm
  _maps/map_files/Planets/JunglePlanet.dmm
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/weather.dm
  code/datums/atmosphere/_atmosphere.dm
  code/datums/atmosphere/planetary.dm
  code/datums/map_config.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_controller.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/floor_is_lava.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/datums/weather/weather_types/void_storm.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/planets.dm
  code/game/objects/items/devices/scanners.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor/iron_floor.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/secrets.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/wizard/lava.dm
  code/modules/map_content/icebox_define.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/planet_templates.dm
  code/modules/overmap/planets/JunglePlanetGenerator.dm
  code/modules/overmap/planets/PlanetGenerator.dm
  code/modules/overmap/planets/planet_templates.dm
  code/modules/ruins/icemoonruin_code/hotsprings.dm
  code/modules/ruins/lavalandruin_code/elephantgraveyard.dm
  tgstation.dme
Labels: Area:Mapping, Status:Test Merged, Type:Feature, Type:Refactor

#257 Remove changelogs that shouldn't have been generated 😿
  html/changelogs/AutoChangeLog-pr-253.yml
  html/changelogs/AutoChangeLog-pr-255.yml
Labels: Type : Fix

#247 Day and Night cycles for planets and Icebox
  code/controllers/subsystem/day_night.dm
  code/controllers/subsystem/mapping.dm
  code/datums/day_night_controller.dm
  code/datums/looping_sounds/weather.dm
  code/datums/map_config.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_controller.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/hailstorm.dm
  code/datums/weather/weather_types/rain.dm
  code/datums/weather/weather_types/sandstorm.dm
  code/datums/weather/weather_types/shroud_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/datums/weather/weather_types/snowfall.dm
  code/modules/map_content/icebox_define.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/planets/planet_templates.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/volcanic_planet.dm
  tgstation.dme
Labels: Area : Sounds, Area : Sprites

#248 One random planet now spawns
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
  code/modules/map_content/tradership/tradership_define.dm
Labels: Area : Sounds, Area : Sprites

#249 Engines are now faster, propulsion engines take less fuel
  code/modules/overmap/propulsion_engine.dm
  code/modules/overmap/shuttle_extension.dm
Labels: Area : Balance

#250 Space Ruin Levels now spawn properly, most maps spawn 3 of them now
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
  code/modules/map_content/deltastation_define.dm
  code/modules/map_content/icebox_define.dm
  code/modules/map_content/kilostation_define.dm
  code/modules/map_content/metastation_define.dm
  code/modules/map_content/tradership/tradership_define.dm
  code/modules/map_content/tramstation_define.dm
  code/modules/overmap/overmap_objects.dm
Labels: Type : Quality of Life

#251 Trading update and fixes
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/trading.dm
  code/datums/map_config.dm
  code/modules/map_content/tradership/tradership_define.dm
  code/modules/trading/_trade_hub.dm
  code/modules/trading/trade_hub_overmap.dm
Labels: Type : Fix

#252 Cigarettes now deal 70% less damage to your lungs
  code/game/objects/items/cigs_lighters.dm
Labels: Area : Balance, Type : Quality of Life

#261 Adds a rock baseturf for the planets
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/desert_planet.dm
  code/modules/overmap/planets/planet_types/jungle_planet.dm
  code/modules/overmap/planets/planet_types/lush_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/snow_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  icons/planet/planet_floors.dmi
Labels: Area : Sprites

#260 Add framework for planetary ruins and some ruins for the planets to spawn
  _maps/RandomRuins/Planet/colony.dmm
  _maps/RandomRuins/Planet/crashed_pod.dmm
  _maps/RandomRuins/Planet/deserted_lab.dmm
  _maps/RandomRuins/Planet/lodge.dmm
  _maps/RandomRuins/Planet/old_pod.dmm
  _maps/RandomRuins/Planet/spider_nest.dmm
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/mapping.dm
  code/datums/ruins.dm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
  code/modules/mapping/ruins.dm
  code/modules/overmap/planets/planet_templates.dm
  code/modules/overmap/planets/planet_types/barren_planet.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/snow_planet.dm
  code/modules/overmap/planets/planet_types/volcanic_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  icons/planet/planet_floors.dmi
  tgstation.dme
Labels: Area : Mapping, Area : Sprites

#265 Bearcat Fixes
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping

#266 Fixes, or should fix, changelog-based labels
  .github/pr_labels.yml
Labels: Area : Repository, Type : Fix

#267 Aaaaaaa labeeels
  .github/workflows/pr_autolabel.yml
Labels: Area : Repository, Type : Fix

#272 Bearcat QoL 2 - Firelocks, Alarms, Departures, Brig
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping

#268 Adds fauna to planets
  code/datums/mapgen/biomes/_biome.dm
  code/datums/weather/weather_types/snowfall.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/overmap/planets/JunglePlanetGenerator.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/desert_planet.dm
  code/modules/overmap/planets/planet_types/jungle_planet.dm
  code/modules/overmap/planets/planet_types/lush_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/snow_planet.dm
  code/modules/overmap/planets/planet_types/volcanic_planet.dm
  code/modules/overmap/planets/planetary_mobs.dm
  icons/planet/planetary_mobs.dmi
  icons/planet/planetary_mobs_effects.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#269 Fixes claw footstep for planetary turfs
  code/modules/overmap/planets/planet_types/barren_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
Labels: Type : Fix

#270 Lumcount now respects area luminosity
  code/modules/lighting/lighting_turf.dm
Labels: Type : Fix

#271 handle automated movement respects AIStatus now
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Type : Fix

#273 Excavation module - conduct archeology today!
  _maps/RandomRuins/Planet/archeological_site.dmm
  _maps/shuttles/exploration_crow.dmm
  code/game/turfs/closed/minerals.dm
  code/modules/excavation/anomalous_crystal.dm
  code/modules/excavation/digsite_component.dm
  code/modules/excavation/digsite_spawner.dm
  code/modules/excavation/excavation_closet.dm
  code/modules/excavation/excavation_exports.dm
  code/modules/excavation/excavation_finds.dm
  code/modules/excavation/excavation_items.dm
  code/modules/excavation/excavation_tools.dm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
  code/modules/overmap/planets/planet_types/jungle_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  icons/excavation/crystal.dmi
  icons/excavation/excavation.dmi
  icons/excavation/excavation_junk.dmi
  icons/excavation/excavation_tools.dmi
  icons/excavation/excavation_unknown.dmi
  icons/excavation/fossils.dmi
  icons/excavation/strange_rock.dmi
  icons/excavation/strange_rock_grayscale.dmi
  tgstation.dme
Labels: Area : Mapping, Area : Sprites, Type : Feature

#275 Adds a treasure hunter fedora to the archeological site ruin
  _maps/RandomRuins/Planet/archeological_site.dmm
Labels: Area : Mapping

#276 Drill Mining and Ore Nodes
  _maps/RandomRuins/Planet/mining_facility.dmm
  _maps/RandomRuins/Planet/old_drill_site.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/shuttles/exploration_crow.dmm
  code/__DEFINES/metal_density.dm
  code/controllers/subsystem/mapping.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/datums/map_config.dm
  code/datums/ore_node.dm
  code/modules/map_content/icebox_define.dm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/mining/metal_density_scanner.dm
  code/modules/mining/mining_drill.dm
  code/modules/overmap/planets/planet_templates.dm
  code/modules/research/designs/mining_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/machines/mining_drill.dmi
  icons/obj/metal_scanner.dmi
  sound/machines/drill/drill_end.ogg
  sound/machines/drill/drill_loop.ogg
  sound/machines/drill/drill_start.ogg
  tgstation.dme
Labels: Area : Mapping, Area : Sounds, Area : Sprites, Type : Feature

#279 Bearcat QoL Part 3: Disposals and Lights
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping

#278 Delayed light switching and sounds
  code/game/machinery/lightswitch.dm
  code/modules/power/lighting.dm
  sound/effects/light/light_on.ogg
  sound/effects/light/lightswitch.ogg
Labels: Area : Sounds, Type : Feature

#281 Fixes moth wings and splits moth fluff from wings
  code/modules/mob/dead/new_player/sprite_accessories/neck.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species_types/humanoid.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mammal.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  icons/mob/sprite_accessory/moth_fluff.dmi
  icons/mob/sprite_accessory/moth_wings.dmi
  tgstation.dme
Labels: Area : Sprites

#283 Fixes zeqetta's splitting into zeq duchesses
  code/modules/overmap/planets/planetary_mobs.dm
Labels: Type : Fix

#284 Trashbag can now be worn in belt slot
  code/game/objects/items/storage/bags.dm
  icons/mob/clothing/belt.dmi
Labels: Area : Sprites, Type : Feature

#285 Removes loneops weight increase from stationary nuke disk
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Type : Quality of Life, Type : Removal

#280 Keyboard noises for computers, modular consoles and laptops
  code/game/machinery/bank_machine.dm
  code/game/machinery/civilian_bounties.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/chef_orders/chef_order.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/computer/launchpad_control.dm
  code/game/machinery/computer/mechlaunchpad.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/computer/station_alert.dm
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/computer/tram_controls.dm
  code/game/machinery/cryopod.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/overmap/overmap_console.dm
  code/modules/research/rdconsole.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/emergency.dm
  code/modules/station_goals/bsa.dm
  code/modules/station_goals/shield.dm
  code/modules/vehicles/mecha/mech_bay.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
Labels: Area : Sounds, Type : Feature

#286 Client-less mobs no longer send their emotes to ghosts through global ghost sight
  code/datums/emotes.dm
Labels: Type : Fix

#291 Update label-based badges on README
  README.md
Labels: Area : Repository, Type : Fix

#287 (Temporary) Species Descriptions
  code/modules/mob/living/carbon/human/species_types/akula.dm
  code/modules/mob/living/carbon/human/species_types/aquatic.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/humanoid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/insect.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mammal.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/robotic.dm
  code/modules/mob/living/carbon/human/species_types/tajaran.dm
  code/modules/mob/living/carbon/human/species_types/unathi.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
Labels: Area : Grammar and Formatting, Type : Feature

#295 [red label fix] Planetary turfs now have planetary atmos
  code/modules/overmap/planets/planetary_objects.dm
Labels: Type : Fix

#297 Keyboard noises for modular consoles and computers
  code/game/machinery/computer/_computer.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/file_system/program.dm
Labels: Area : Sounds, Area : UI/UX, Type : Feature

#300 Turf Fires and Flamethrower Rework
  code/controllers/subsystem/turf_fire.dm
  code/game/machinery/firealarm.dm
  code/game/objects/effects/turf_fire.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/effects/turf_fire.dmi
  tgstation.dme
Labels: Area : Balance, Area : Sprites, Type : Feature

#302 Chest bursting no longer gibs
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Area : Balance

#303 Luxury bar cruiser
  _maps/shuttles/whiteship_the_barrows.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/white_ship.dm
Labels: Area : Mapping

#306 Luxury chilldown cargo
  _maps/shuttles/luxury_chilldown.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/luxury.dm
  tgstation.dme
Labels: Area : Mapping

#307 Luxury shuttle ironwrought
  _maps/shuttles/luxury_ironwrought.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/luxury.dm
Labels: Area : Mapping

#311 Fixes corvid snout
  code/modules/mob/dead/new_player/sprite_accessories/snout.dm
  icons/mob/sprite_accessory/snouts.dmi
Labels: Area : Sprites

#308 Runtime Errors for The Chilldown Removal
  _maps/shuttles/luxury_chilldown.dmm
Labels: Area : Mapping

#313 Traders paycheck and credits tweak
  code/__DEFINES/trading.dm
  code/modules/trading/_trader.dm
  code/modules/trading/traders/goods.dm
Labels: Area : Balance, Type : Feature

#315 Adds Archeology trader + trading tweaks
  code/modules/excavation/anomalous_crystal.dm
  code/modules/trading/_trade_hub.dm
  code/modules/trading/_trader.dm
  code/modules/trading/bought_goods/goods.dm
  code/modules/trading/sold_goods/goods.dm
  code/modules/trading/traders/goods.dm
Labels: Area : Balance, Type : Feature

#316 Ghosts now start with normal lighting alpha
  code/modules/mob/dead/observer/observer.dm
Labels: Type : Quality of Life

#317 Removes designs of quantum pads and quantum spin inverters from research nodes
  code/modules/research/techweb/all_nodes.dm
Labels: Type : Removal

#318 Fixes shuttle freeform port cleanup
  code/modules/shuttle/shuttle.dm
Labels: Type : Fix

#319 Removes cash redemption from the mining vendor
  code/modules/mining/machine_vending.dm
Labels: Type : Removal

#312 Console for Shuttle Purchasing and Common Dock Improvements
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/common_vulture.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/shuttles/whiteship_box.dmm
  code/__DEFINES/shuttle_purchase.dm
  code/controllers/subsystem/shuttle.dm
  code/game/area/areas/shuttles.dm
  code/modules/mining/laborcamp/laborshuttle.dm
  code/modules/mining/mine_items.dm
  code/modules/ruins/spaceruin_code/caravanambush.dm
  code/modules/shuttle/common_docks.dm
  code/modules/shuttle/exploration.dm
  code/modules/shuttle/shuttle_purchase_console.dm
  code/modules/shuttle/sold_shuttles.dm
  code/modules/shuttle/white_ship.dm
  tgstation.dme
Labels: Area : Mapping, Type : Feature

#322 Lower TCOMMS looping vol
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Type : Quality of Life

#323 Fixes jungle turfs having wrong gas mixes set
  code/game/turfs/open/floor/plating/planet.dm
Labels: Type : Fix

#324 Turfs now properly restore areas after shuttle movements
  code/game/turfs/change_turf.dm
  code/game/turfs/turf.dm
  code/modules/shuttle/on_move.dm
Labels: Type : Fix

#326 Lighting transitions to indoors areas from day/night
  code/datums/day_night_controller.dm
  code/game/area/area_day_night.dm
  code/game/area/areas.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/ruins/space.dm
  code/modules/shuttle/on_move.dm
  icons/effects/daynight_blend.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#327 Fixes outdoors planetary areas having power
  code/modules/overmap/planets/planetary_objects.dm
Labels: Type : Fix

#329 Moves safe's item insertion to LateInitialize to support spawners
  code/game/objects/structures/safe.dm
Labels: Type : Fix

#330 One Habitable Planet Ruin
  _maps/RandomRuins/Planet/abandoned_factory.dmm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
Labels: Area : Mapping

#331 Adds Rubble, explosions make rubble
  code/game/objects/structures/rubble.dm
  code/game/turfs/closed/walls.dm
  icons/obj/structures/rubble.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature
