Repository hrzntal/horizon, pull requests merged in 2021-09, with the labels that each got.

#509 Adds more ruins
  _maps/RandomRuins/Planet/heyheypeople.dmm
  _maps/RandomRuins/SpaceRuins/derelict2.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/syndicatewreck01.dmm
  _maps/RandomRuins/SpaceRuins/tinybox.dmm
  code/datums/ruins/space.dm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
Labels: Area : Mapping

#512 FTV Bearcat: Misc Fixes, Changes + "EVA" in big bold air quotes
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping

#514 Multi-Cyclelinks - Ports /tg/ #60675
  code/game/machinery/doors/airlock.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Type : Mirror, Area : Mapping, Type : Feature

#407 New Sprites - Janitorial | Also some little functionality
  icons/obj/janitor.dmi
Labels: Status : Test Merged, Area : Sprites, Type : Feature
