Repository hrzntal/horizon, pull requests merged in 2021-12, with the labels that each got.

#561 Updates Chair Sprite
  icons/obj/chairs.dmi
Labels: Area : Sprites

#562 Adds Metal Rubble
  code/game/objects/structures/rubble.dm
  code/game/turfs/closed/walls.dm
  icons/obj/structures/rubble.dmi
Labels: Area : Sprites

#563 You can now stop holding onto things in 0g
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
Labels: Type : Feature

#558 Turf Fire subsystem code improvements
  code/controllers/subsystem/turf_fire.dm
Labels: Type : Fix

#557 Pollution tweaks, improvements
  code/__DEFINES/pollution.dm
  code/controllers/subsystem/pollution.dm
  code/datums/components/grillable.dm
  code/datums/components/temporary_pollution_emission.dm
  code/datums/elements/pollution_emitter.dm
  code/game/objects/effects/turf_fire.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mining/mining_drill.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/emote.dm
  code/modules/pollution/air_refresher.dm
  code/modules/pollution/perfumes.dm
  code/modules/pollution/pollutant.dm
  code/modules/pollution/pollutants/pollutants_generic.dm
  code/modules/pollution/pollution.dm
  code/modules/reagents/chemistry/holder.dm
  icons/effects/pollution.dmi
Labels: Area : Sprites, Type : Feature

#565 Fixes up multiz atmos connection, cleans some things up in general #63270
  code/__DEFINES/atmospherics.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/open/openspace.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/shuttle/shuttle_roof.dm
Labels: Type : Fix

#566 Blind Effects and improvements
  code/__DEFINES/layers.dm
  code/_onclick/hud/plane_master.dm
  code/datums/components/footstep.dm
  code/game/atoms_movable.dm
  code/game/blind_effect.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/projectiles/projectile.dm
  icons/effects/blind_effects.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#568 Fixes grilles queueing SMOOTHING indefinetly. [important]
  code/game/objects/structures/grille.dm
Labels: Type : Fix

#570 Actually fixes reinforced plasma window spawner
  code/game/objects/effects/spawners/structure.dm
Labels: Type : Fix

#576 Flashlight resprite
  icons/obj/lighting.dmi
Labels: Area : Sprites

#577 Some fixes to virtual levels
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mapping/space_management/multiz_helpers.dm
Labels: Type : Fix

#578 Creates /turf/open/space/openspace
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
Labels: Type : Fix, Type : Refactor
