Repository hrzntal/horizon, pull requests merged in 2021-08, with the labels that each got.

#483 Fixes reported job issues
  code/controllers/subsystem/job.dm
  code/modules/map_content/tradership/tradership_jobs.dm
Labels: Type : Fix

#484 Reinforced mining hardsuit icon for digitigrades
  icons/horizon/mob/clothing/mutant/suit_digi.dmi
Labels: Area : Sprites, Type : Fix

#485 Fixes job flags for the bearcat jobs
  code/modules/map_content/tradership/tradership_jobs.dm
Labels: Type : Fix

#493 [Port] Makes diagonal movement euclidean
  code/__DEFINES/maths.dm
  code/modules/mob/mob_movement.dm
Labels: Type : Mirror, Area : Balance, Type : Quality of Life

#489 FTV Bearcat missing equipment + fixes
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping, Type : Fix

#242 Fixes hairstyles, refactors human_face.dmi
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/dead/new_player/sprite_accessories/facial_hair.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/organs/eyes.dm
  icons/mob/human_face.dmi
  icons/mob/sprite_accessory/human_face.dmi
  icons/mob/sprite_accessory/human_facialhair.dmi
  icons/mob/sprite_accessory/human_hair.dmi
  tgstation.dme
Labels: Status : Test Merged, Area : Sprites, Type : Fix, Type : Refactor

#495 Fixes meaty ores halting the MC with connect_loc overhead
  code/modules/meteors/meteors.dm
Labels: Type : Fix

#496 Exotic languages for exotic cultures
  code/__DEFINES/culture.dm
  code/modules/client/culture/culture/culture_generic.dm
Labels: Type : Feature

#500 Disallow objects with client mobs to be sold or bountied off
  code/modules/trading/_bought_goods.dm
  code/modules/trading/_trader_bounty.dm
Labels: Type : Fix

#501 More bounties and gas bounties for traders
  code/modules/trading/_trader_bounty.dm
  code/modules/trading/bounties/trader_bounties.dm
  code/modules/trading/traders/food.dm
  code/modules/trading/traders/goods.dm
Labels: Type : Feature

#504 Getting floored now only sets resting for client mobs
  code/modules/mob/living/living.dm
Labels: Type : Fix

#408 New Sprites - Floors
  icons/turf/floors.dmi
Labels: Status : Test Merged, Area : Sprites

#412 New Sprites - PowerNet
  icons/obj/power.dmi
Labels: Status : Test Merged, Area : Sprites

#502 Delivery Run missions from Traders
  code/__DEFINES/trading.dm
  code/controllers/subsystem/trading.dm
  code/modules/overmap/_OVERMAP_HELPERS.dm
  code/modules/overmap/sun_system.dm
  code/modules/paperwork/paper.dm
  code/modules/trading/_delivery_run.dm
  code/modules/trading/_trader.dm
  code/modules/trading/delivery_runs/delivery_runs.dm
  code/modules/trading/trade_machines.dm
  code/modules/trading/traders/food.dm
  code/modules/trading/traders/goods.dm
  icons/obj/items/delivery_package.dmi
  icons/overmap/overmap.dmi
  icons/overmap/overmap_turfs.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#409 New Sprites - Windows | structures.dmi cleanup
  code/game/objects/structures/table_frames.dm
  icons/obj/smooth_structures/plasma_window.dmi
  icons/obj/smooth_structures/reinforced_window.dmi
  icons/obj/smooth_structures/rplasma_window.dmi
  icons/obj/smooth_structures/tinted_window.dmi
  icons/obj/smooth_structures/window.dmi
  icons/obj/structures.dmi
Labels: Status : Test Merged, Area : Sprites, Type : Removal

#506 Lowers trader bounty and delivery gain chances
  code/modules/trading/_trader.dm
  code/modules/trading/traders/food.dm
Labels: Area : Balance

#507 Fixes loadout items not being applied to roundstarted people
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/_job.dm
Labels: Type : Fix
