Repository hrzntal/horizon, pull requests merged in 2021-07, with the labels that each got.

#336 Triples rubble integrity
  code/game/objects/structures/rubble.dm
Labels: Area : Balance, Type : Quality of Life

#337 Delayed lighting tweaks and fixes
  code/modules/power/lighting.dm
Labels: Type : Fix, Type : Quality of Life

#338 Planetary turf refactor
  _maps/RandomRuins/Planet/abandoned_factory.dmm
  _maps/RandomRuins/Planet/archeological_site.dmm
  _maps/RandomRuins/Planet/colony.dmm
  _maps/RandomRuins/Planet/mining_facility.dmm
  _maps/RandomRuins/Planet/old_drill_site.dmm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/plating/planet.dm
  code/modules/overmap/planets/planet_types/barren_planet.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/desert_planet.dm
  code/modules/overmap/planets/planet_types/jungle_planet.dm
  code/modules/overmap/planets/planet_types/lush_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/snow_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  icons/planet/planet_grass.dmi
  tgstation.dme
Labels: Area : Mapping, Area : Sprites, Type : Fix

#339 Shuttle Platforms for purchasing
  _maps/shuttles/common_platform_large.dmm
  _maps/shuttles/common_platform_medium.dmm
  _maps/shuttles/common_platform_small.dmm
  _maps/shuttles/common_vulture.dmm
  code/game/area/areas/shuttles.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/modules/shuttle/common_docks.dm
  code/modules/shuttle/sold_shuttles.dm
Labels: Area : Mapping, Type : Feature, Type : Fix

#333 HRV FoxCat Armor
  code/modules/clothing/spacesuits/chronosuit.dm
  hrzn/modules/hrvfoxcat/code/modules/clothing/hrvfoxcat.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#340 Concrete walls
  code/game/turfs/closed/wall/misc_walls.dm
  icons/turf/walls/concrete_wall.dmi
Labels: Area : Sprites, Type : Feature

#335 Adds more wall signs (Deck signs, new signs, lots of small variants too)
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/game/objects/structures/signs/signs_warning.dm
  icons/obj/decals.dmi
Labels: Area : Sprites

#344 Fixes to daynight blend and its mask tweak
  code/game/area/area_day_night.dm
  code/game/area/areas.dm
  icons/effects/daynight_blend.dmi
Labels: Area : Sprites, Type : Fix, Type : Quality of Life

#345 Weather now occurs ~33% less frequently
  code/datums/weather/weather_controller.dm
Labels: Area : Balance

#346 Fixes bandaged limbs being able to be bandaged again, and small examine fix
  code/game/objects/items/stacks/medical.dm
  code/modules/surgery/bodyparts/bodypart_aid.dm
Labels: Type : Fix

#348 Possibly fixes issues with day/night and thunder overlays sticking
  code/controllers/subsystem/day_night.dm
  code/datums/day_night_controller.dm
  code/datums/weather/weather.dm
  icons/effects/daynight_blend.dmi
Labels: Area : Sprites, Type : Fix

#341 Supercruiser Aggregeddon and Mezzeriah
  _maps/shuttles/supercruiser_aggregeddon.dmm
  _maps/shuttles/supercruiser_mezzeriah.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/supercruiser.dm
  tgstation.dme
Labels: Area : Mapping, Area : Sprites

#351 Fixes mining drills being left behind by shuttles
  code/modules/mining/mining_drill.dm
Labels: Type : Fix

#352 Fixes shuttles no longer being able to dock on planetary turfs
  code/modules/overmap/freeform_docker.dm
Labels: Type : Fix

#353 Fixes mineral rock attackby() not calling parent (excavation fix)
  code/game/turfs/closed/minerals.dm
Labels: Type : Fix

#354 Fixes and clarifies the admin debug ore scanner
  code/modules/mining/equipment/mineral_scanner.dm
Labels: Type : Fix

#355 Fixes bad code in the trader datum
  code/modules/trading/_trader.dm
Labels: Type : Refactor

#356 Increases flora density on lush planets by ~40%
  code/modules/overmap/planets/planet_types/lush_planet.dm
Labels: Area : Balance

#357 Changes to flora integrity
  code/game/objects/structures/flora.dm
Labels: Area : Balance

#358 Fixes parallax oddities and overmap shuttle parallax
  code/_onclick/hud/parallax.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_shuttle_process.dm
  code/modules/overmap/shuttle_control_component.dm
  code/modules/shuttle/shuttle.dm
Labels: Type : Fix

#359 Makes food crafting faster.
  code/modules/food_and_drinks/recipes/food_mixtures.dm
Labels: Type : Quality of Life

#360 Adds Cargo Shorts and a T-Shirt Combo
  code/modules/client/loadout/uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  icons/horizon/mob/clothing/mutant/under/uniform_digi.dmi
  icons/horizon/mob/clothing/uniform.dmi
  icons/horizon/obj/clothing/uniforms.dmi
Labels: Area : Sprites

#362 Bearcat QoL Part 4: Doors, Bars, Fans and Signs
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
Labels: Area : Mapping, Type : Quality of Life

#364 Basic Mining Kit
  code/modules/mining/machine_vending.dm
Labels: Type : Quality of Life

#361 Ruins Removed
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  _maps/RandomRuins/SpaceRuins/originalcontent.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/lavaland.dm
  config/spaceruinblacklist.txt
Labels: Area : Configuration, Area : Mapping, Warn : Config Update

#365 Fixes parallax runtime
  code/_onclick/hud/parallax.dm
Labels: Type : Fix

#369 Fixes nulls in managed_overlays
  code/game/atoms_movable.dm
Labels: Type : Fix

#367 Engine effects - fire plume and looping sound
  _maps/map_files/tradership/tradership3.dmm
  code/__DEFINES/dcs/signals.dm
  code/datums/components/engine_effect.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/effects/fireplume.dm
  code/game/shuttle_engines.dm
  code/modules/overmap/propulsion_engine.dm
  code/modules/overmap/shuttle_extension.dm
  icons/effects/fireblue.dmi
  sound/machines/engine/engineend.ogg
  sound/machines/engine/engineloop.ogg
  sound/machines/engine/enginestart.ogg
  tgstation.dme
Labels: Area : Mapping, Area : Sounds, Area : Sprites, Type : Feature

#363 Cypress' Mega Ruin Map Redux!
  _maps/RandomRuins/Planet/abandoned_factory.dmm
  _maps/RandomRuins/Planet/crashed_pod.dmm
  _maps/RandomRuins/Planet/deserted_lab.dmm
  _maps/RandomRuins/Planet/lodge.dmm
  _maps/RandomRuins/SpaceRuins/DJstation.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/asteroid1.dmm
  _maps/RandomRuins/SpaceRuins/asteroid4.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/derelict2.dmm
  _maps/RandomRuins/SpaceRuins/derelict3.dmm
  _maps/RandomRuins/SpaceRuins/derelict4.dmm
  _maps/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/RandomRuins/SpaceRuins/way_home.dmm
Labels: Area : Mapping

#370 Small trader tweaks
  code/modules/trading/sold_goods/food.dm
  code/modules/trading/sold_goods/goods.dm
  code/modules/trading/traders/food.dm
  code/modules/trading/traders/goods.dm
Labels: Area : Balance, Status : Test Merged, Type : Feature

#375 Planetary turfs inherit a proper baseturf now
  code/modules/overmap/planets/planetary_objects.dm
Labels: Type : Fix

#376 Fixes space turfs in abandoned factory ruin
  _maps/RandomRuins/Planet/abandoned_factory.dmm
Labels: Area : Mapping, Type : Fix

#377 Digsite fix and clarification
  code/modules/excavation/digsite_component.dm
Labels: Type : Fix

#381 Fixes light overlays on multi z openspace
  code/modules/power/lighting.dm
Labels: Type : Fix

#388 Traders now can have a limited amount of "stock" they'll purchase, and can purchase reagents
  code/modules/trading/_bought_goods.dm
  code/modules/trading/_trader.dm
  code/modules/trading/bought_goods/goods.dm
  code/modules/trading/trade_machines.dm
  code/modules/trading/traders/goods.dm
Labels: Area : Balance, Type : Feature

#368 Shuttle Roofs and more multi-z functionality
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/obj_flags.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/elements/turf_transparency.dm
  code/game/sound.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle_roof.dm
  tgstation.dme
Labels: Type : Feature

#380 Makes existing allergy quirk nicer, adds extreme subtype
  code/controllers/subsystem/processing/quirks.dm
  code/datums/quirks/negative.dm
Labels: Area : Balance, Type : Feature

#389 Leopard Tail
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  icons/mob/sprite_accessory/tails.dmi
Labels: Area : Sprites, Type : Feature

#390 Coins no longer have any force
  code/modules/mining/ores_coins.dm
Labels: Area : Balance, Type : Fix

#391 Wrench can be used in setting/repairing bone surgery
  code/modules/surgery/bone_mending.dm
Labels: Type : Feature

#392 Fireplaces are now craftable and burn longer
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/fireplace.dm
  icons/obj/fireplace.dmi
Labels: Area : Sprites, Type : Feature, Type : Quality of Life

#393 Better hiding/showing of private parts
  code/modules/mob/dead/new_player/sprite_accessories/genitals.dm
Labels: Type : Fix

#394 Bodytype backend for all appearance stuff, fixes and cleanups
  code/__DEFINES/preferences.dm
  code/__HELPERS/customization/mobs.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/customization/lists.dm
  code/modules/admin/create_mob.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/body_markings/body_marking_sets.dm
  code/modules/mob/dead/new_player/body_markings/body_markings.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  code/modules/mob/dead/new_player/sprite_accessories/vox.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
Labels: Type : Fix, Type : Refactor

#395 RnD designs for new horizon content
  code/modules/overmap/mining_laser.dm
  code/modules/research/designs/excavation_designs.dm
  code/modules/research/designs/overmap_machines_designs.dm
  code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Type : Feature

#397 Plated Catwalks + Footstep Override element
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/footsteps.dm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/layers.dm
  code/datums/components/footstep.dm
  code/datums/elements/footstep_override.dm
  code/game/objects/items/stacks/catwalk.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/industrial_lift.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/overmap/planets/planetary_objects.dm
  code/modules/power/cable.dm
  code/modules/recycling/disposal/pipe.dm
  icons/obj/items/catwalk_item.dmi
  icons/obj/smooth_structures/catwalk_plated.dmi
  icons/obj/smooth_structures/catwalk_plated_dark.dmi
  icons/obj/smooth_structures/catwalk_plated_smooth.dmi
  tgstation.dme
Labels: Area : Sounds, Area : Sprites, Type : Feature

#399 Lowers margin from traders from 30% to 15%, and price variance to 20% from 25%
  code/modules/trading/_trader.dm
Labels: Area : Balance

#400 Climbing over things, railing fix
  code/datums/elements/climbable.dm
  code/game/objects/structures/railings.dm
Labels: Type : Fix

#401 Fixes caltrop component not knowing the real source's name
  code/datums/elements/caltrop.dm
  code/game/objects/items/dice.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/mob/living/simple_animal/hostile/cockroach.dm
  code/modules/power/lighting.dm
Labels: Type : Fix

#402 Fixes a turf signal unregistration I missed, makes the transparent turf element detach (#60064)
  code/datums/elements/turf_transparency.dm
Labels: Type : Fix, Type : Mirror

#403 Lowers ship ambience volume
  code/game/area/areas.dm
Labels: Type : Quality of Life

#404 Overmap hard del and logic fixes
  code/controllers/subsystem/overmap.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_visuals.dm
  code/modules/overmap/shuttle_control_component.dm
Labels: Type : Fix

#405 Fixes runechat calculating an improper amount of lines
  code/datums/chatmessage.dm
Labels: Type : Fix

#411 New Sprites - Lighting
  icons/obj/lighting.dmi
  icons/obj/lighting_overlay.dmi
Labels: Area : Sprites

#413 New Sprites - Medkits
  icons/obj/storage.dmi
Labels: Area : Sprites

#415 New Sprites - Crates
  icons/obj/crates.dmi
Labels: Area : Sprites

#416 New Sprites - Plating
  icons/turf/floors.dmi
Labels: Area : Sprites

#418 Fixes a missing angled opening bracket for SPAN
  code/__DEFINES/span.dm
Labels: Type : Fix

#414 Two new planetary ruins.
  _maps/RandomRuins/Planet/abandoned_containment.dmm
  _maps/RandomRuins/Planet/weather_station.dmm
  code/modules/map_content/ruins/planetary/planet_ruins.dm
Labels: Area : Mapping

#419 Typing indicator now disappears after sending an emote
  code/modules/mob/mob_say.dm
Labels: Type : Fix

#420 The mining laser design now prints the circuitboard, not the machine
  code/modules/research/designs/overmap_machines_designs.dm
Labels: Type : Fix

#421 Fixes dynamic lighting overlays
  code/game/objects/effects/overlays.dm
Labels: Type : Fix

#422 Buffs the mech plasma cutter blasts to 25 dmg from 10 dmg
  code/modules/projectiles/projectile/special/plasma.dm
Labels: Area : Balance

#423 Removes topic check from trader console UI interact
  code/modules/trading/trade_machines.dm
Labels: Type : Quality of Life

#424 Fixes ghost hair overlays
  code/modules/mob/dead/observer/observer.dm
Labels: Type : Fix

#425 Fixes smooth plated catwalk icon and plated catwalk description
  code/game/objects/structures/lattice.dm
  icons/obj/smooth_structures/catwalk_plated_smooth.dmi
Labels: Area : Sprites, Type : Fix

#431 Removes coughing from nicotine withdrawal
  code/modules/reagents/withdrawal/generic_addictions.dm
Labels: Type : Fix

#433 Disclaimer about dock connection in Shuttle Purchase Console
  code/modules/shuttle/shuttle_purchase_console.dm
Labels: Type : Quality of Life

#435 Fixes kilo station common dock wrong direction
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Area : Mapping, Type : Fix

#436 Pref characters as ghost roles
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/awaymissions/corpse.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Type : Feature

#437 Dynamic lighting fix for real
  code/datums/components/overlay_lighting.dm
  code/game/objects/effects/overlays.dm
Labels: Type : Fix

#438 Fixes some improper areas in space ruins
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
Labels: Area : Mapping, Type : Fix

#443 Nerfs excavation exports
  code/modules/excavation/excavation_exports.dm
  code/modules/trading/bought_goods/goods.dm
Labels: Area : Balance

#442 Trader Update - Bounties, Manifests and Logs
  code/__DEFINES/trading.dm
  code/modules/trading/_bought_goods.dm
  code/modules/trading/_trader.dm
  code/modules/trading/_trader_bounty.dm
  code/modules/trading/bounties/trader_bounties.dm
  code/modules/trading/trade_machines.dm
  code/modules/trading/traders/weaponry.dm
  tgstation.dme
Labels: Type : Feature, Type : Refactor

#444 Lightswitch Construction/Deconstruction
  code/game/machinery/lightswitch.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  icons/obj/power.dmi
  icons/obj/wallframe.dmi
Labels: Area : Sprites, Type : Feature

#445 Transit Zones Functionalities
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/overmap.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/components/transit_handler.dm
  code/datums/transit_instance.dm
  code/game/turfs/open/space/transit.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/overmap/freeform_docker.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/overmap_shuttle_process.dm
  code/modules/overmap/overmap_transportable.dm
  code/modules/overmap/shuttle_control_component.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/shuttle.dm
  tgstation.dme
Labels: Area : Mapping, Type : Feature, Type : Refactor

#447 Fixes day night cycle layers
  code/__DEFINES/layers.dm
  code/datums/day_night_controller.dm
  code/game/area/area_day_night.dm
Labels: Type : Fix

#448 Transit velocity doesn't throw things if they're against something
  code/datums/transit_instance.dm
Labels: Type : Quality of Life

#449 Station and Space levels are now selflooping
  code/__DEFINES/maps.dm
  code/datums/map_config.dm
  code/modules/map_content/multiz_debug_define.dm
  code/modules/map_content/tramstation_define.dm
Labels: Type : Feature

#446 Dominant Handed-ness
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
Labels: Type : Feature

#452 Drills and braces are now lavaproof
  code/modules/mining/mining_drill.dm
Labels: Type : Fix

#383 Pipe overlays overhaul and bitmasking
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/gas_recipe_machines/crystallizer.dm
  code/modules/atmospherics/machinery/pipes/bridge_pipe.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/simple.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/pipes/smart.dm
  icons/obj/atmospherics/pipes/layer_manifold_underlays.dmi
  icons/obj/atmospherics/pipes/pipe_underlays.dmi
  icons/obj/atmospherics/pipes/pipes_bitmask.dmi
Labels: Area : Sprites, Type : Fix, Type : Refactor

#434 Industrial Lifts complete rework and big feature update
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/industrial_lift.dm
  code/controllers/subsystem/industrial_lift.dm
  code/controllers/subsystem/processing/tramprocess.dm
  code/datums/industrial_lift/lift_controller.dm
  code/datums/industrial_lift/lift_waypoint.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/tram_controls.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/structures/industrial_lift.dm
  code/game/objects/structures/industrial_lift_structures.dm
  code/modules/assembly/doorcontrol.dm
  icons/obj/machines/lift_status_display.dmi
  icons/obj/structures/elevator_control.dmi
  sound/lifts/elevator_ding.ogg
  sound/lifts/lift_loop/lift_end.ogg
  sound/lifts/lift_loop/lift_loop.ogg
  sound/lifts/lift_loop/lift_start.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/TramControl.js
Labels: Area : Mapping, Area : Sounds, Area : Sprites, Area : UI/UX, Type : Feature, Type : Refactor

#455 Borb plushie in loadout
  code/modules/client/loadout/backpack.dm
Labels: Type : Feature

#456 Getting floored will set your resting status
  code/modules/mob/living/living.dm
Labels: Type : Quality of Life

#458 Overmap Hazards affect Transit Zones + small fixes
  code/datums/transit_instance.dm
  code/game/turfs/open/space/transit.dm
  code/modules/meteors/meteors.dm
  code/modules/overmap/overmap_hazards.dm
Labels: Type : Feature, Type : Fix

#457 Adds a pocket crowbar to the internals box
  code/game/objects/items/storage/boxes.dm
Labels: Type : Quality of Life

#454 Pollution System
  code/__DEFINES/customization/loadout.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/pollution.dm
  code/__DEFINES/subsystems.dm
  code/_onclick/hud/plane_master.dm
  code/controllers/subsystem/pollution.dm
  code/controllers/subsystem/processing/pollution_emitters.dm
  code/datums/components/grillable.dm
  code/datums/components/temporary_pollution_emission.dm
  code/datums/elements/pollution_emitter.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/turf_fire.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/maintenance.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/client/loadout/backpack.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mining/mining_drill.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/emote.dm
  code/modules/pollution/air_refresher.dm
  code/modules/pollution/perfumes.dm
  code/modules/pollution/pollutant.dm
  code/modules/pollution/pollutants/pollutants_generic.dm
  code/modules/pollution/pollution.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/vending/wardrobes.dm
  icons/obj/items/air_refresher.dmi
  icons/obj/items/perfume.dmi
  tgstation.dme
Labels: Area : Sprites, Status : Test Merged, Type : Feature

#462 Ports dynamic lighting PR's
  code/datums/components/overlay_lighting.dm
  code/game/objects/effects/overlays.dm
  code/game/turfs/change_turf.dm
Labels: Type : Fix, Type : Mirror, Type : Refactor

#463 Removes the liquid pump from the mining trader
  code/modules/trading/sold_goods/goods.dm
  code/modules/trading/traders/goods.dm
Labels: Type : Fix, Type : Removal

#464 Missing border flag for railings
  code/game/objects/structures/railings.dm
Labels: Type : Fix

#465 Fixes a mapping runtime with forgottenship
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
Labels: Area : Mapping, Type : Fix

#466 Fixes a runtime that would leave everyone naked #60327
  code/controllers/subsystem/ticker.dm
Labels: Type : Fix, Type : Mirror

#467 Fixes an underlay movable lighting runtime #60336
  code/datums/components/overlay_lighting.dm
Labels: Type : Fix, Type : Mirror

#468 Emission caps for pollution
  code/__DEFINES/pollution.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/hydroponics/grown/towercap.dm
Labels: Type : Fix

#469 Fixes pollution change turf runtime
  code/game/turfs/change_turf.dm
Labels: Type : Fix

#473 Fixes camo desert eagle sprites
  icons/obj/guns/ballistic.dmi
Labels: Area : Sprites, Type : Fix

#471 Port Meat Fix
  code/datums/components/food/edible.dm
  code/game/objects/items/food/meat.dm
Labels: Type : Fix, Type : Mirror

#480 Fixes missing mini-egun mode states
  icons/obj/guns/energy.dmi
Labels: Area : Sprites, Type : Fix, Type : Quality of Life

#479 Port of SStimer subsystem fixes, from RU SS220 Paradise
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/timer.dm
  config/config.txt
Labels: Area : Configuration, Type : Fix, Type : Mirror, Warn : Config Update

#476 Add carbon check on clap emote can-run proc
  hrzn/modules/emotes/code/emotes.dm
Labels: Type : Fix
