Repository hrzntal/horizon, pull requests merged in 2021-11, with the labels that each got.

#533 Deathroll Dice
  code/game/objects/items/dice.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/client/loadout/backpack.dm
  code/modules/vending/games.dm
  icons/obj/items/deathroll_dice.dmi
Labels: Area : Sprites, Type : Feature

#535 Fixes some wall smoothing and translations
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/wall/misc_walls.dm
Labels: Type : Fix

#534 Changed Vulture Descriptions
  code/modules/shuttle/sold_shuttles.dm
Labels: Area : Grammar and Formatting

#531 [MDB IGNORE] Windows resprite and rework
  _maps/RandomRuins/Planet/lodge.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/tradership/tradership1.dmm
  _maps/map_files/tradership/tradership2.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tradership/tradership4.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/layers.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/paint.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/walls.dm
  code/modules/mapping/mapping_helpers/paint_wall_helper.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/effects/paint_helpers.dmi
  icons/obj/smooth_structures/clockwork_window.dmi
  icons/obj/smooth_structures/grille.dmi
  icons/obj/smooth_structures/low_wall.dmi
  icons/obj/smooth_structures/plasma_window.dmi
  icons/obj/smooth_structures/plastitanium_window.dmi
  icons/obj/smooth_structures/pod_window.dmi
  icons/obj/smooth_structures/reinforced_window.dmi
  icons/obj/smooth_structures/rice_window.dmi
  icons/obj/smooth_structures/rplasma_window.dmi
  icons/obj/smooth_structures/shuttle_window.dmi
  icons/obj/smooth_structures/tinted_window.dmi
  icons/obj/smooth_structures/window.dmi
  icons/obj/smooth_structures/window_reinforced.dmi
  icons/obj/structures.dmi
  tgstation.dme
Labels: Area : Mapping, Area : Sprites, Type : Feature

#536 Wall mounted & Boozemat & Smartfridge & Security TV sprite upgrades
  code/game/machinery/firealarm.dm
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/monitors.dmi
  icons/obj/power.dmi
  icons/obj/stationobjs.dmi
  icons/obj/vending.dmi
Labels: Area : Sprites

#539 Keys and locks expansion, mineral door resprite
  code/__DEFINES/keys_locks.dm
  code/game/objects/items/keys_locks.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/pimpin_ride.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/secway.dm
  code/modules/vehicles/vehicle_key.dm
  icons/obj/closet.dmi
  icons/obj/crates.dmi
  icons/obj/doors/mineral_doors.dmi
  icons/obj/items/keys_locks.dmi
  icons/obj/vehicles.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#537 Fix chat verb uses legacy alert
  code/modules/tgui_panel/external.dm
Labels: Type : Fix

#544 Ore veins and crystals, diffuser box. Industrial mining preparations
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/greyscale/json_configs/ore_vein_crystal_large.json
  code/datums/greyscale/json_configs/ore_vein_crystal_tiny.json
  code/datums/greyscale/json_configs/ore_vein_large.json
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/reflector.dm
  code/modules/mining/ore_veins.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/structures.dmi
  icons/obj/structures/crystal_gags.dmi
  icons/obj/structures/crystal_small_gags.dmi
  icons/obj/structures/crystal_tiny_gags.dmi
  icons/obj/structures/ore_vein_gags.dmi
  icons/obj/structures/ore_vein_small_gags.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#545 Catwalks can now only smooth with themselves again
  code/game/objects/structures/lattice.dm
Labels: Type : Fix

#546 Fixes throw mode putting you on click cooldown despite not throwing #62749
  code/_onclick/click.dm
Labels: Type : Fix

#548 Variable cleanup PR ports.
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/modules/vending/_vending.dm
Labels: Type : Fix

#549 Removes unused list in molotov cocktails
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
Labels: Type : Fix

#553 Fixes cardboard box overlays
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Labels: Type : Fix

#551 Fixes icon states and overlays for broken air alarm
  code/modules/atmospherics/machinery/airalarm.dm
Labels: Type : Fix

#552 Fixes missing reinforced plasma window spawner
  code/game/objects/effects/spawners/structure.dm
Labels: Type : Fix

#554 Fixes suit storage worn states
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Area : Sprites, Type : Fix

#555 Properly sets species information when creating a new preference file.
  code/modules/client/preferences.dm
Labels: Type : Fix

#556 Fixes consistency in low wall and window smoothing
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/modules/mining/equipment/survival_pod.dm
Labels: Type : Fix
