Repository hrzntal/horizon, pull requests merged in 2021-01, with the labels that each got.

#47 Cultural and Languages update
  code/__DEFINES/culture.dm
  code/__DEFINES/customization/jobs.dm
  code/__DEFINES/customization/lists.dm
  code/__DEFINES/economy.dm
  code/__HELPERS/customization/global_lists.dm
  code/controllers/subsystem/job.dm
  code/datums/dna.dm
  code/datums/traits/neutral.dm
  code/modules/client/culture/cultural_info.dm
  code/modules/client/culture/culture/_culture.dm
  code/modules/client/culture/culture/culture_generic.dm
  code/modules/client/culture/culture/culture_lizard.dm
  code/modules/client/culture/faction/_faction.dm
  code/modules/client/culture/faction/faction_generic.dm
  code/modules/client/culture/location/_location.dm
  code/modules/client/culture/location/location_generic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/language/gutter.dm
  code/modules/language/language_holder.dm
  code/modules/language/russian.dm
  code/modules/language/selenian.dm
  code/modules/language/spacer.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/surgery/organs/tongue.dm
  icons/horizon/misc/language.dmi
  tgstation.dme
Labels: test merged

#76 [TG Patch] Frame stacking fix and unit test addition.
  code/__DEFINES/construction.dm
  code/__HELPERS/unsorted.dm
  code/game/atoms_movable.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/objs.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/rcd.dm
Labels: Ready For Review And Merge

#77 [TG Patch] Cyborg modules renamed to models
  code/__DEFINES/exosuit_fab.dm
  code/__DEFINES/robots.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/wires.dm
  code/__HELPERS/roundend.dm
  code/_onclick/hud/robot.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/wires/robot.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/weaponry.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/mob/living/silicon/robot/robot_model.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/robotact.dm
  code/modules/ninja/suit/ninjaDrainAct.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/surgery/surgery.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  config/game_options.txt
  strings/tips.txt
  tgstation.dme
  tgui/packages/tgui/interfaces/BorgPanel.js
  tgui/packages/tgui/interfaces/NtosCyborgRemoteMonitor.js
  tgui/packages/tgui/interfaces/RoboticsControlConsole.js
Labels: Ready For Review And Merge

#79 [TG Patch] Disabled postinstall scripts until they're fixed in yarn
  tgui/.yarnrc.yml
Labels: Ready For Review And Merge

#80 [TG Patch] mining keys to open tendrills crates buyable with miner points
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/storage/belt.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/machine_vending.dm
  icons/obj/lavaland/artefacts.dmi
Labels: Ready For Review And Merge

#81 [TG Patch] Splits Grasp of Rust using intents
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
Labels: Ready For Review And Merge

#82 [TG Patch] 1:1 HUD layout fix
  code/__DEFINES/hud.dm
  code/_onclick/hud/human.dm
Labels: Ready For Review And Merge

#83 [TG Patch] Removes the persistent hold on a tmp savefile.
  code/__HELPERS/icons.dm
Labels: Ready For Review And Merge

#61 [TM ONLY] 24 Add Heaters to Air alarms
  code/modules/atmospherics/machinery/airalarm.dm
  tgui/packages/tgui/interfaces/AirAlarm.js
Labels: Test Merged

#8 Adds SQL Logging - by missfoxie
  SQL/tgstation_schema.sql
  code/controllers/configuration/entries/general.dm
  code/game/atoms.dm
Labels: Feature, Test Merged

#95 [TG Patch] Prevents the most common case of fire settling with an excited group
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/air.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Ready For Review And Merge
