Repository hrzntal/horizon, pull requests merged in 2022-11, with the labels that each got.

#1213 Skyline v1 Release
  _maps/_basemap.dm
  _maps/map_files/skylineship/skylineship.dmm
  _maps/shuttles/cargo_skyline.dmm
  _maps/shuttles/common_vista.dmm
  _maps/shuttles/emergency_skyline.dmm
  _maps/skylineship.json
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/datums/id_trim/jobs.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/area/space_station_13_areas.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/command.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/jobs/job_types/skylineship_joboutfits.dm
  code/modules/map_content/skylineship/skylineship_define.dm
  code/modules/map_content/skylineship/skylineship_jobs.dm
  code/modules/mapping/mapping_helpers/paint_wall_helper.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/shuttle/common_docks.dm
  code/modules/trading/_trade_hub.dm
  config/maps.txt
  horizon.dme
  icons/obj/card.dmi
  icons/obj/decals.dmi
Labels: Area : Mapping, Area : Sprites, Area : Configuration, ⚠️ Warn : Config Update

#1215 Update TGS DMAPI workflow: checkout v3; commit id
  .github/workflows/update_tgs_dmapi.yml
Labels: Area : Repository

#1197 Plumbing Refactor
  code/__DEFINES/layers.dm
  code/__DEFINES/plumbing.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/plumbing/reaction_chamber.dm
  code/game/objects/items/RCD.dm
  code/game/objects/structures/lavaland/geyser.dm
  code/modules/plumbing/ducts.dm
  code/modules/plumbing/plumbers/_plumb_machinery.dm
  icons/hud/radial.dmi
  icons/obj/plumbing/connects.dmi
  icons/obj/plumbing/fluid_ducts.dmi
Labels: Area : Sprites, Type : Refactor, Type : Feature, Area : Gameplay
