Repository hrzntal/horizon, pull requests merged in 2022-05, with the labels that each got.

#862 Fixes wall scanning experiments
  code/game/turfs/closed/walls.dm
  code/modules/experisci/experiment/types/scanning_material.dm
Labels: Type : Fix

#863 Repository spring cleaning
  .github/workflows/ci_suite.yml
  .gitignore
  SQL/admin_import_2018-02-03.py
  SQL/ban_conversion_2018-10-28.py
  SQL/errofreedatabase.sql
  SQL/feedback_conversion_2017-11-12.py
  SQL/optimisations_2017-02-19.sql
  SQL/populate_key_2018-07-09.py
  SQL/tgstation_schema_prefixed.sql
  TGS3.json
  byond-extools.dll
  code/__DEFINES/_tick.dm
  code/_compile_options.dm
  code/game/objects/items/RCD.dm
  code/game/world.dm
  code/modules/vehicles/motorized_wheelchair.dm
  config/config.txt
  dependencies.sh
  tools/CreditsTool/CreditsTool.csproj
  tools/CreditsTool/CreditsTool.exe
  tools/CreditsTool/Program.cs
  tools/CreditsTool/UpdateCreditsDMI.sh
  tools/CreditsTool/remappings.txt
  tools/Runtime Condenser/Main.cpp
  tools/SQLAlertEmail/email_config.ps1
  tools/SQLAlertEmail/email_script.ps1
  tools/WebhookProcessor/github_webhook_processor.php
  tools/WebhookProcessor/secret.php
  tools/midi2piano/README.txt
  tools/midi2piano/easygui/__init__.py
  tools/midi2piano/midi/__init__.py
  tools/midi2piano/midi/midi.py
  tools/midi2piano/midi2piano.py
  tools/midi2piano/pyperclip/__init__.py
  tools/midi2piano/pyperclip/clipboards.py
  tools/midi2piano/pyperclip/exceptions.py
  tools/midi2piano/pyperclip/windows.py
  tools/tgs4_scripts/PreCompile.sh
Labels: Area : Tools, Area : Repository, Area : Database, Area : Configuration, Warn : Config Update, Type : Removal

#864 Balances lavaland megafauna
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Area : Balance

#866 Removes the intern announcer
  code/datums/announcers/intern_announcer.dm
  code/datums/station_traits/neutral_traits.dm
  sound/ai/intern/alerts/1.ogg
  sound/ai/intern/alerts/10.ogg
  sound/ai/intern/alerts/11.ogg
  sound/ai/intern/alerts/12.ogg
  sound/ai/intern/alerts/13.ogg
  sound/ai/intern/alerts/14.ogg
  sound/ai/intern/alerts/2.ogg
  sound/ai/intern/alerts/3.ogg
  sound/ai/intern/alerts/4.ogg
  sound/ai/intern/alerts/5.ogg
  sound/ai/intern/alerts/6.ogg
  sound/ai/intern/alerts/7.ogg
  sound/ai/intern/alerts/8.ogg
  sound/ai/intern/alerts/9.ogg
  sound/ai/intern/aliens.ogg
  sound/ai/intern/animes.ogg
  sound/ai/intern/commandreport/1.ogg
  sound/ai/intern/commandreport/2.ogg
  sound/ai/intern/commandreport/3.ogg
  sound/ai/intern/granomalies.ogg
  sound/ai/intern/intercept.ogg
  sound/ai/intern/ionstorm.ogg
  sound/ai/intern/meteors.ogg
  sound/ai/intern/outbreak5.ogg
  sound/ai/intern/outbreak7.ogg
  sound/ai/intern/poweroff.ogg
  sound/ai/intern/poweron.ogg
  sound/ai/intern/radiation.ogg
  sound/ai/intern/shuttlecalled.ogg
  sound/ai/intern/shuttledock.ogg
  sound/ai/intern/shuttlerecalled.ogg
  sound/ai/intern/spanomalies.ogg
  sound/ai/intern/welcome/1.ogg
  sound/ai/intern/welcome/2.ogg
  sound/ai/intern/welcome/3.ogg
  sound/ai/intern/welcome/4.ogg
  sound/ai/intern/welcome/5.ogg
  sound/ai/intern/welcome/6.ogg
  tgstation.dme
Labels: Area : Sounds, Type : Removal

#870 Fixes a rare overlay lighting bug
  code/datums/components/overlay_lighting.dm
Labels: Type : Fix

#871 New fire alarm sound loop
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/area/areas.dm
  code/game/machinery/firealarm.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  goon/sound/machinery/FireAlarm.ogg
  sound/machines/fire_alarm/FireAlarm1.ogg
  sound/machines/fire_alarm/FireAlarm2.ogg
  sound/machines/fire_alarm/FireAlarm3.ogg
  sound/machines/fire_alarm/FireAlarm4.ogg
Labels: Area : Sounds

#872 Emoting now makes a blue typing indicator
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  icons/mob/talk.dmi
Labels: Area : Sprites

#873 Fixes bedsheet direction, spawn and icon state issues
  code/game/objects/structures/bedsheet_bin.dm
  icons/obj/bedsheets.dmi
Labels: Area : Sprites, Type : Fix

#874 Navigation beacons now display under catwalks
  code/__DEFINES/layers.dm
  code/game/machinery/navbeacon.dm
Labels: Type : Fix

#875 Fixes a cut type of cable coil being invisible
  code/modules/power/cable.dm
Labels: Type : Fix

#876 You can now add logs to the fireplace, fireplace improvements
  code/game/objects/structures/fireplace.dm
  code/modules/hydroponics/grown/towercap.dm
Labels: Type : Fix, Area : Balance

#877 Fixes inconsistent pipe layering
  code/__HELPERS/piping_colors_lists.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Type : Fix

#879 Renames thermomachines to heat pumps
  _maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/tradership/tradership3.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/luxury_ironwrought.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_tram.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/unit_tests/machine_disassembly.dm
  icons/obj/atmospherics/components/heat_pump.dmi
Labels: Area : Mapping, Area : Sprites, Area : Grammar and Formatting

#880 Removes deadchat plays component
  code/__DEFINES/vv.dm
  code/datums/components/deadchat_control.dm
  code/game/atoms_movable.dm
  code/modules/events/immovable_rod.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/singularity/singularity.dm
  tgstation.dme
Labels: Type : Removal

#882 Removes beauty element
  code/datums/components/fantasy/prefixes.dm
  code/datums/elements/beauty.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/datums/materials/hauntium.dm
  code/datums/materials/meat.dm
  code/datums/materials/pizza.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/statues.dm
  tgstation.dme
Labels: Type : Removal

#881 Removes liver and mind traits and related effects
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/components/squeak.dm
  code/game/objects/items/food/pastries.dm
  code/modules/antagonists/nukeop/clownop.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/psychologist.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/map_content/tradership/tradership_jobs.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/withdrawal/generic_addictions.dm
  code/modules/surgery/organs/liver.dm
Labels: Status : Merge Conflict, Type : Removal

#883 Removed the 'cheesy_message' from TGS when the last admin leaves.
  code/modules/client/client_procs.dm
Labels: Area : Administration, Type : Quality of Life

#884 Monkeys no longer screech while idle
  code/datums/ai/monkey/monkey_controller.dm
Labels: Type : Removal

#885 Descriptor systems for humans
  code/_globalvars/descriptor.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/descriptor/_descriptor.dm
  code/modules/mob/living/carbon/human/descriptor/descriptors.dm
  code/modules/mob/living/carbon/human/descriptor/human_descriptor.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/robotic.dm
  tgstation.dme
Labels: Type : Feature

#889 New sprites for pumps and porta scrubbers
  icons/obj/atmos.dmi
Labels: Area : Sprites

#891 Wormhole new icon
  icons/obj/objects.dmi
Labels: Area : Sprites

#890 Fireaxe and Flamethrower new icons
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/axes_lefthand.dmi
  icons/mob/inhands/weapons/axes_righthand.dmi
  icons/mob/inhands/weapons/flamethrower_lefthand.dmi
  icons/mob/inhands/weapons/flamethrower_righthand.dmi
  icons/obj/flamethrower.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/wallmounts.dmi
Labels: Area : Sprites

#892 New cigarette accessories and new icons for such
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/vending/cigarette.dm
  icons/mob/clothing/mask.dmi
  icons/obj/cigarettes.dmi
  icons/obj/clothing/masks.dmi
Labels: Area : Sprites

#893 New icons for chemical tanks
  icons/obj/chemical_tanks.dmi
Labels: Area : Sprites

#894 Emissive overlay for light fixtures
  code/modules/power/lighting.dm
  icons/obj/lighting_overlay.dmi
Labels: Area : Sprites

#895 Fixes a few chemtanks sprites being offset by one pixel
  icons/obj/chemical_tanks.dmi
Labels: Area : Sprites

#897 A few paint_wall fixes
  code/modules/mapping/mapping_helpers/paint_wall_helper.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Type : Fix

#901 Fixes Heat Pump UI and layering
  code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/HeatPump.js
Labels: Area : UI/UX, Type : Fix

#902 Fixes loadouts being broken for completely new prefs
  code/modules/client/preferences.dm
  code/modules/client/preferences_loadout.dm
Labels: Type : Fix

#905 Adds 6 new beak variants to choose from
  code/modules/mob/dead/new_player/sprite_accessories/snout.dm
  icons/mob/sprite_accessory/snouts.dmi
Labels: Area : Sprites

#912 New crushed cans!
  icons/obj/janitor.dmi
Labels: Area : Sprites

#926 Fixes looking down a z level
  code/game/objects/structures/industrial_lift.dm
  code/modules/mob/living/living.dm
Labels: Type : Fix, Area : Gameplay

#927 Fixes cases of string use of assigned_role
  code/__DEFINES/is_helpers.dm
  code/datums/mind.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Type : Fix

#928 Adresses muteness and language discrepencacies
  code/__DEFINES/culture.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/warden.dm
Labels: Type : Quality of Life, Area : Gameplay

#937 New windows sprites
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/greyscale/json_configs/structures/fulltile_window.json
  code/game/objects/structures/window.dm
  code/game/turfs/closed/_closed.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/obj/smooth_structures/window.dmi
  icons/obj/smooth_structures/window_reinforced.dmi
Labels: Area : Sprites

#938 Mining shuttles no longer use the overmap
  code/modules/mining/mine_items.dm
Labels: Type : Removal, Area : Gameplay

#948 Fixes up ambitions and antag normal objectives
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Type : Fix, Area : Gameplay

#950 Fixes gravity from disabled gravity generators
  code/game/atoms.dm
Labels: Type : Fix, Area : Gameplay

#951 Proper dir offsets and mapping types for bathroom objects
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
Labels: Type : Fix

#942 Plated catwalk improvements
  code/game/objects/items/stacks/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  icons/obj/plated_catwalk.dmi
  icons/obj/smooth_structures/catwalk_plated.dmi
  icons/obj/smooth_structures/catwalk_plated_dark.dmi
  icons/obj/smooth_structures/catwalk_plated_smooth.dmi
Labels: Area : Sprites, Area : Balance

#944 You can no longer purchase the mining shuttle
  code/modules/shuttle/sold_shuttles.dm
Labels: Type : Removal

#953 Deconstructing showers
  code/game/objects/structures/shower.dm
Labels: Type : Feature

#900 Logarithmic Audio Volume
  code/__DEFINES/sound.dm
  code/__HELPERS/roundend.dm
  code/game/sound.dm
Labels: Area : Sounds, Type : Quality of Life

#904 Change roundend volume to logarithmic 50%
  code/controllers/subsystem/ticker.dm
Labels: Status : Test Merge - Deployed, Area : Sounds, Type : Quality of Life, Status : Test Merge - Candidate

#941 Loadout Option Update: Attack of the Cones
  code/modules/client/loadout/backpack.dm
  code/modules/client/loadout/glasses.dm
  code/modules/client/loadout/head.dm
  code/modules/client/loadout/mask.dm
  code/modules/client/loadout/neck.dm
  code/modules/client/loadout/shoes.dm
  code/modules/client/loadout/suit.dm
  code/modules/client/loadout/uniform.dm
Labels: Area : Balance, Type : Quality of Life

#959 Large input box for subtler anti ghost
  code/modules/mob/mob_say.dm
Labels: Area : UI/UX, Type : Quality of Life

#960 Makes storyteller events around 30% less frequent
  code/__DEFINES/storyteller.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update, Area : Balance

#962 Less synthflesh amount to unhusk someone
  code/__DEFINES/reagents.dm
Labels: Type : Fix, Area : Balance, Area : Gameplay

#859 Inflatable walls!
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/inflatables.dm
  icons/obj/items/inflatables.dmi
  icons/obj/structures/inflatables.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature, Area : Gameplay

#967 Robotic humans no longer raise temperature when in crit
  code/modules/mob/living/carbon/human/species_types/robotic.dm
Labels: Area : Balance

#968 Clearing turfs in the map parser
  code/__HELPERS/unsorted.dm
  code/game/objects/effects/spawners/clear.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/ruins.dm
Labels: Type : Fix

#965 Synthetic Anthromorphs and more sanity
  code/__HELPERS/customization/mobs.dm
  code/modules/mob/living/carbon/human/species_types/robotic.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update

#970 Fixes directionals for showers and sinks
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
Labels: Type : Fix

#939 Fix: Med Sec Checkpoint - Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Area : Mapping, Type : Fix

#978 Ports Hardened Soles and Excitable Quirks
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/elements/caltrop.dm
  code/datums/quirks/good.dm
  code/datums/quirks/neutral.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Type : Feature, Area : Gameplay

#979 Allows Gasmasks to be stored in toolbelts
  code/game/objects/items/storage/belt.dm
Labels: Area : Balance

#993 Larger input box for subtle emote
  code/modules/mob/mob_say.dm
Labels: Area : UI/UX, Type : Quality of Life

#996 Fixes missing names for base jumpskirt and jumpsuit
  code/modules/clothing/under/color.dm
Labels: Type : Fix, Area : Grammar and Formatting

#990 Remove ghostrole spawn message for using existing characters
  code/modules/awaymissions/corpse.dm
Labels: Area : UI/UX, Type : Removal

#995 Fixes overlay management conflict
  code/game/atoms.dm
Labels: Area : Sprites, Type : Fix

#997 Observers dont go through a buggy do_after to appraise art objects
  code/datums/elements/art.dm
Labels: Type : Fix, Area : Gameplay

#998 Terminals are now under catwalks
  code/__DEFINES/layers.dm
  code/modules/power/terminal.dm
Labels: Area : Sprites, Type : Quality of Life

#1004 Frills, ears, horns show up on robotic heads
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
Labels: Area : Sprites, Type : Fix

#991 Fixes killer saunas
  code/game/objects/structures/sauna_oven.dm
Labels: Type : Fix, Area : Gameplay

#1002 Remove brain trauma strings, godwoken syndrome, merge dumbness with speech impairment
  code/__DEFINES/misc.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/text.dm
  code/_globalvars/traits.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/special.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mutations/speech.dm
  code/datums/voice_of_god_command.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/mob_helpers.dm
  strings/traumas.json
Labels: Type : Removal, Type : Quality of Life

#1005 Hermit survival changes
  _maps/RandomRuins/IceRuins/icemoon_underground_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
Labels: Area : Mapping, Area : Balance

#1007 Adds a flag for objects to allow transparency if they block multiz
  code/__DEFINES/obj_flags.dm
  code/datums/elements/turf_transparency.dm
  code/game/objects/structures/industrial_lift.dm
Labels: Type : Fix, Type : Quality of Life

#1012 Quieter industrial lifts
  code/datums/industrial_lift/lift_controller.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/structures/industrial_lift_structures.dm
Labels: Type : Quality of Life

#1011 Touches up the MS Vulture
  _maps/shuttles/common_vulture.dmm
Labels: Area : Mapping, Type : Fix, Area : Balance

#1006 Character editor background choice, sprite ports - Beep boop 🤖
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/genitals.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  code/modules/mob/dead/new_player/sprite_accessories/snout.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  icons/mob/sprite_accessory/genitals/penis_onmob.dmi
  icons/mob/sprite_accessory/genitals/vagina_onmob.dmi
  icons/mob/sprite_accessory/human_hair.dmi
  icons/mob/sprite_accessory/synthanthro_ears.dmi
  icons/mob/sprite_accessory/synthanthro_snouts.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Area : Sprites

#1014 Fixes Vox not getting proper headwear sprite variants
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
Labels: Area : Sprites, Type : Fix

#1018 Deposit Credits in PDA/Tablet
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/modular_computers/computers/item/computer.dm
Labels: Type : Quality of Life, Area : Gameplay

#1019 Fixed a pixel error on the blue digi pyjamas
  icons/mob/clothing/under/misc.dmi
Labels: Area : Sprites

#1013 Windoors take slightly longer to automatically close after bumping to them
  code/game/machinery/doors/windowdoor.dm
Labels: Area : Balance

#1015 Some hunger tweaks
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Type : Fix, Area : Balance

#1021 LOOC while unconcious/dead + Administrative LOOC & Toggle
  code/__DEFINES/preferences.dm
  code/__DEFINES/span.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/looc.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Area : UI/UX, Area : Administration, Type : Quality of Life

#1022 New hawaiian shirts!
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  code/modules/client/loadout/suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Area : Mapping, Area : Sprites

#1024 Fixed background_state sanitization
  code/modules/client/preferences_savefile.dm
Labels: Type : Fix

#1031 [s] Fixed oversight on looc loop
  code/modules/client/verbs/looc.dm
Labels: Type : Fix, Area : Administration

#992 Bioluminescent plants use the static lighting system
  code/modules/hydroponics/plant_genes.dm
Labels: Type : Quality of Life

#1032 Fixes funny bug with voluntary 0g movement
  code/modules/mob/living/living_movement.dm
Labels: Type : Fix, Area : Gameplay

#1034 Quieter PACMAN soundloop
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Area : Sounds, Type : Quality of Life

#1033 Fixes ruins not clearing turfs and adds that option to the template spawn verb
  code/datums/shuttles.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/mapping/map_template.dm
Labels: Type : Fix

#981 Adds a bunch more wing/moth wing/arm wing/leg wing options
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  icons/mob/sprite_accessory/moth_wings.dmi
  icons/mob/sprite_accessory/wingswide.dmi
Labels: Area : Sprites

#1025 Updates cargo & miner jumpsuits
  code/modules/clothing/under/jobs/cargo.dm
  icons/mob/clothing/under/cargo.dmi
Labels: Area : Sprites

#1030 Adds the MS Petrel
  _maps/shuttles/common_petrel.dmm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/common_docks.dm
  code/modules/shuttle/sold_shuttles.dm
Labels: Area : Mapping
