Repository hrzntal/horizon, pull requests merged in 2022-01, with the labels that each got.

#579 ALLOW_RANDOM_EVENTS is now HALT_STORYTELLER config
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/gamemode.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update

#580 Fixes blind effects playing for vision corrected people
  code/game/blind_effect.dm
Labels: Type : Fix

#581 Rune chat for messages is now gray and small
  code/datums/chatmessage.dm
  icons/ui_icons/chat/chat_icons.dmi
Labels: Area : Sprites

#583 Parallax fix and removed not needed animate
  code/_onclick/hud/parallax.dm
Labels: Type : Fix

#584 Fixes ambience controller runtime error
  code/modules/ambience/ambience_controller.dm
Labels: Type : Fix

#586 Fixes alternate wallet action click chain
  code/datums/components/storage/concrete/wallet.dm
Labels: Type : Fix

#587 pickweight maintenance and fixes
  code/__HELPERS/_lists.dm
  code/datums/ai_laws.dm
  code/datums/looping_sounds/item_sounds.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/machinery/computer/arcade/orion.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/turfs/closed/minerals.dm
  code/modules/meteors/meteors.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Type : Fix

#588 Make laying down on WEST/EAST non-randomized
  code/modules/mob/living/carbon/carbon.dm
Labels: Type : Quality of Life

#590 Fixes bugs failing CI
  code/controllers/subsystem/mapping.dm
  code/modules/holodeck/computer.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/unit_tests/unit_test.dm
Labels: Type : Fix

#594 Demodularizes and improves typing indicator
  code/_onclick/click.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  hrzn/modules/typing_indicator/code/mob.dm
  hrzn/modules/typing_indicator/icons/typing_indicator.dmi
  hrzn/modules/typing_indicator/readme.md
  tgstation.dme
Labels: Area : Sprites

#595 Fixes scraped turfs not having planetary atmospherics
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
Labels: Type : Fix

#596 Better paint colors for survival pod walls
  code/game/turfs/closed/wall/mineral_walls.dm
Labels: Area : Sprites

#597 Adds shelves and better transferItemToLoc
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/inventory.dm
  icons/obj/items_and_weapons.dmi
  icons/obj/objects.dmi
Labels: Area : Sprites, Type : Feature

#591 Bigger transit padding and reservation
  code/__DEFINES/maps.dm
  code/__DEFINES/shuttles.dm
Labels: Type : Feature

#598 Ambience Update
  code/__DEFINES/ambient_sounds.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/modules/ambience/ambience_controller.dm
  code/modules/ambience/ambient_sounds/ambient_sounds.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/research/nanites/nanite_program_hub.dm
  sound/ambience/emitters/air_pump_idle.ogg
  sound/ambience/emitters/periodic_beep.ogg
Labels: Area : Sounds

#601 Add 2.5x pixel scaling
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
Labels: Type : Feature

#603 Emissive maintenance. Emissives for cigs and hazard stripes.
  code/__DEFINES/lighting.dm
  code/__HELPERS/lighting.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wintercoats.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid_update_icons.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head/winterhood.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suits/wintercoat.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
Labels: Area : Sprites, Type : Refactor

#604 Better cooldown for disposal flush sound
  code/modules/recycling/disposal/bin.dm
Labels: Type : Fix

#606 Save interview status
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/interview/interview.dm
  code/modules/mob/dead/new_player/login.dm
Labels: Type : Fix

#582 Better returns for emoting without the first parameter
  code/modules/mob/living/emote.dm
Labels: Type : Fix

#605 Managed Jukeboxes
  code/__DEFINES/jukebox_defines.dm
  code/__DEFINES/sound.dm
  code/controllers/subsystem/jukebox.dm
  code/datums/jukebox_datums.dm
  code/datums/map_zones.dm
  code/game/machinery/dance_machine.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  tgstation.dme
Labels: Area : Sounds, Type : Feature

#593 Speaking into radios makes a noise
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  sound/effects/radio/common.ogg
  sound/effects/radio/security.ogg
Labels: Area : Sounds

#608 Changes tcomms ambience into server ambience
  code/__DEFINES/ambient_sounds.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/ambience/ambient_sounds/ambient_sounds.dm
  sound/machines/tcomms/tcomms_mid1.ogg
  sound/machines/tcomms/tcomms_mid2.ogg
  sound/machines/tcomms/tcomms_mid3.ogg
  sound/machines/tcomms/tcomms_mid4.ogg
  sound/machines/tcomms/tcomms_mid5.ogg
  sound/machines/tcomms/tcomms_mid6.ogg
  sound/machines/tcomms/tcomms_mid7.ogg
Labels: Area : Sounds

#611 Removes ENFORCE_HUMAN_AUTHORITY and FORCE_RANDOM_NAMES and Appearance bans
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/ert.dm
  code/datums/helper_datums/getrev.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/ert.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update

#612 Makes wormholes more fun
  code/datums/map_zones.dm
  code/modules/events/wormholes.dm
  icons/obj/objects.dmi
Labels: Area : Sprites, Type : Feature

#613 Remove obsolete or dead tools
  .gitlab-ci.yml
  tools/HubMigrator/HubMigrator.dm
  tools/HubMigrator/HubMigrator.dme
  tools/Redirector/Configurations.dm
  tools/Redirector/Redirect_Tgstation.dmb
  tools/Redirector/Redirect_Tgstation.dme
  tools/Redirector/Redirector.dm
  tools/Redirector/config.txt
  tools/Redirector/skin.dmf
  tools/Redirector/textprocs.dm
  tools/Upload tgstation.rsc to external FTP/upload_rsc.bat
  tools/discordRoleScript/README.MD
  tools/discordRoleScript/Script.py
  tools/minibot/LICENCE-bot_folder.txt
  tools/minibot/config.py
  tools/minibot/minibot.py
  tools/minibot/nudge.py
Labels: Area : Tools, Type : Removal

#614 Reduce jaws-of-life head-change sfx volume
  code/game/objects/items/tools/crowbar.dm
Labels: Area : Sounds, Type : Quality of Life

#618 Asay for deadmins through a verb
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/mobs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/deadmin_asay.dm
  tgstation.dme
Labels: Area : Administration

#619 Makes Mold an event & Mold tweaks
  code/modules/events/mold.dm
  code/modules/mold/mold_structures.dm
  tgstation.dme
Labels: Area : Balance, Type : Feature

#617 Storyteller update. Better pop thresholds. Pop scalling. Msg pref and tweaks
  code/__DEFINES/storyteller.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/gamemode.dm
  code/game/gamemodes/storyteller.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/false_alarm.dm
  code/modules/events/spontaneous_appendicitis.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update, Area : Administration, Area : Balance

#620 Towels and some code improvements
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/emergency_cruise.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/shuttles/emergency_monastery.dmm
  _maps/templates/holodeck_lounge.dmm
  _maps/templates/shelter_3.dmm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/spawners/scatter.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/cannon.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/watercloset.dm
  code/modules/cargo/packs.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/reagent_containers/towel_and_rag.dm
  code/modules/vending/wardrobes.dm
  icons/obj/items/towel/towel.dmi
  icons/obj/items/towel/towel_lefthand.dmi
  icons/obj/items/towel/towel_righthand.dmi
  icons/obj/items/towel/towel_worn.dmi
  icons/obj/structures.dmi
  sound/items/towelwhip.ogg
  sound/items/towelwipe.ogg
  tgstation.dme
Labels: Area : Mapping, Area : Sprites, Area : Sounds

#623 Jukebox, ambience and sound improvements
  code/__DEFINES/jukebox_defines.dm
  code/__DEFINES/sound.dm
  code/controllers/subsystem/jukebox.dm
  code/datums/jukebox_datums.dm
  code/game/machinery/dance_machine.dm
  code/modules/ambience/ambience_controller.dm
  code/modules/ambience/ambient_sounds/ambient_sounds.dm
  code/modules/mob/living/carbon/life.dm
Labels: Area : Sounds

#622 Pubby Atmos fixes and additions
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Fix

#631 Pubby fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Fix

#632 Fixes runtime errors with Pubby APCS
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping

#616 Remove round-end display
  code/__HELPERS/roundend.dm
  code/_globalvars/game_modes.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
Labels: Area : UI/UX, Type : Removal

#637 Adds Sauna Ovens. Hot and steamy
  code/__DEFINES/construction.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/sauna_oven.dm
  icons/obj/structures/sauna_oven.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#628 Add maintainers to codeowners for critical paths
  .github/CODEOWNERS
Labels: Area : Repository

#638 Pubby Fixes MK2
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping

#643 Fix up two gun sprites
  icons/obj/guns/ballistic.dmi
  icons/obj/guns/energy.dmi
Labels: Area : Sprites, Type : Fix

#648 Fixes gravity generator issues on bearcat
  _maps/map_files/tradership/tradership3.dmm
Labels: Area : Mapping, Type : Fix

#647 Makes the igniter button sprite more consistent
  icons/obj/stationobjs.dmi
Labels: Area : Sprites

#650 Removed rouge shutter in atmos
  _maps/map_files/tradership/tradership3.dmm
Labels: Area : Mapping

#651 Boomboxes
  code/__DEFINES/jukebox_defines.dm
  code/datums/jukebox_datums.dm
  code/game/objects/items/boombox.dm
  code/modules/vending/games.dm
  icons/obj/items/boombox/bb_lefthand.dmi
  icons/obj/items/boombox/bb_righthand.dmi
  icons/obj/items/boombox/boombox.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#654 Fixes storytellers being unpickable after setting one
  code/controllers/subsystem/gamemode.dm
Labels: Type : Fix

#658 Have belt items cover up private parts
  code/modules/mob/dead/new_player/sprite_accessories/genitals.dm
Labels: Type : Fix

#655 Change death broadcast on death to read real_name
  code/modules/mob/living/death.dm
Labels: Type : Fix

#666 Pubby Fixes and Additions
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping

#667 Attack returns and more jammy active state for boombox
  code/game/objects/items/boombox.dm
  icons/obj/items/boombox/bb_lefthand.dmi
  icons/obj/items/boombox/bb_righthand.dmi
  icons/obj/items/boombox/boombox.dmi
Labels: Area : Sprites

#672 Storyteller tweaks. Better reoccurance and better pop scale
  code/__DEFINES/storyteller.dm
  code/modules/events/_event.dm
  config/game_options.txt
Labels: Area : Configuration, Warn : Config Update

#685 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Area : Repository

#689 Removes ping display and middleware from tgui-panel
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui-panel/game/middleware.js
  tgui/packages/tgui-panel/index.js
  tgui/packages/tgui-panel/ping/PingIndicator.js
  tgui/packages/tgui-panel/ping/actions.js
  tgui/packages/tgui-panel/ping/constants.js
  tgui/packages/tgui-panel/ping/index.js
  tgui/packages/tgui-panel/ping/middleware.js
  tgui/packages/tgui-panel/ping/reducer.js
  tgui/packages/tgui-panel/ping/selectors.js
  tgui/packages/tgui-panel/styles/components/Ping.scss
  tgui/packages/tgui-panel/styles/main.scss
Labels: Area : UI/UX, Type : Removal

#690 Removes telegraph messages from weather
  code/datums/weather/weather.dm
Labels: Type : Removal, Type : Quality of Life

#694 Fixes water freezing into ice when dispensing it
  code/__DEFINES/reagents.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Type : Mirror, Type : Fix

#697 [MIRROR] Fixes some stupid behavior in computer hardware code.
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_components.dm
  code/modules/modular_computers/hardware/CPU.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/portable_disk.dm
  code/modules/modular_computers/hardware/recharger.dm
Labels: Type : Mirror, Type : Fix

#693 Splits jukebox song name into artist and title, sorts boombox songlist
  code/controllers/subsystem/jukebox.dm
  code/datums/jukebox_datums.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/items/boombox.dm
  config/jukebox_music/README.txt
Labels: Area : Configuration, Warn : Config Update

#695 Fed's Emote Pack 1
  code/modules/mob/living/emote.dm
  sound/voice/catchirp.ogg
  sound/voice/credits.txt
  sound/voice/feline_hiss.ogg
  sound/voice/feline_purr.ogg
  sound/voice/nyaha.ogg
  sound/voice/nyahaha1.ogg
  sound/voice/nyahaha2.ogg
  sound/voice/nyahehe.ogg
  sound/voice/rawr.ogg
  sound/voice/scream_raptor.ogg
  sound/voice/scream_rodent.ogg
  sound/voice/trills.ogg
  sound/voice/warbles.ogg
  sound/voice/whine1.ogg
  sound/voice/whine2.ogg
  sound/voice/yelp1.ogg
  sound/voice/yelp2.ogg
Labels: Area : Sounds

#701 Fix language key issues, add avian tongue
  code/modules/language/gutter.dm
  code/modules/language/schechi.dm
  code/modules/language/selenian.dm
  code/modules/language/voltaic.dm
  code/modules/language/vox.dm
  code/modules/mob/living/carbon/human/species_types/teshari.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/surgery/organs/tongue.dm
Labels: Area : UI/UX, Type : Fix

#699 Re-enable emote keybinds
  code/datums/keybinding/emote.dm
Labels: Type : Quality of Life

#706 Added Reload verb for jukebox in server tab
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/jukebox_reload.dm
  tgstation.dme
Labels: Area : Administration

#710 Changed Window Icon to HRZN
  icons/hrzn-64.png
  icons/tg_32.png
  interface/skin.dmf
Labels: Area : Sprites

#715 Fortune cookies now give you your fortune
  code/game/objects/items/food/pastries.dm
Labels: Type : Mirror, Type : Fix

#712 Pubby Fixes and changes Vol 3
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping

#716 Fixes FRET hardsuit not being spaceproof
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Type : Fix, Area : Administration

#717 Added Painting save function to LibComputer
  code/modules/library/lib_machines.dm
Labels: Area : UI/UX, Type : Feature, Type : Quality of Life

#692 Ports TG Sofa + Bed changes from #62169 and #62813
  code/__DEFINES/dye_keys.dm
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/greyscale/json_configs/bench_corner.json
  code/datums/greyscale/json_configs/bench_left.json
  code/datums/greyscale/json_configs/bench_middle.json
  code/datums/greyscale/json_configs/bench_right.json
  code/game/machinery/washing_machine.dm
  code/game/objects/buckling.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/beds_chairs/sofa.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/obj/bedsheets.dmi
  icons/obj/lavaland/survival_pod.dmi
  icons/obj/sofa.dmi
Labels: Area : Sprites, Type : Fix, Type : Feature

#725 More Pubby fixes: Pipes and Cables
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Fix

#729 Wormhole event improvements
  code/modules/events/wormholes.dm
Labels: Area : Balance, Type : Feature

#726 Selective continuous integrations
  .github/gbp.toml
  .github/workflows/ci_suite.yml
  .github/workflows/gbp.yml
  .github/workflows/gbp_collect.yml
Labels: Area : Repository
