Repository hrzntal/horizon, pull requests merged in 2022-06, with the labels that each got.

#1044 Icebox atmosphere changes
  code/datums/atmosphere/planetary.dm
Labels: Area : Balance, Type : Quality of Life

#1045 Removes extra unnessecary species sanitization
  code/modules/client/preferences.dm
Labels: Type : Fix

#1049 Light fixtures always setDir on Initialize() for pixel offsets
  code/modules/power/lighting.dm
Labels: Type : Fix

#1058 Fixes dir-shifted objects being misaligned after a shuttle is rotated.
  code/modules/shuttle/shuttle_rotate.dm
Labels: Type : Fix

#1059 Fixes Administrative LOOC mode not working
  code/modules/client/verbs/looc.dm
Labels: Type : Fix

#1064 Fixes new dresses not being able to adjust
  code/modules/clothing/under/skirt_dress.dm
  icons/obj/clothing/under/dress.dmi
Labels: Area : Sprites

#1056 Adds Long Range Holopads to Petrel and Vulture
  _maps/shuttles/common_petrel.dmm
  _maps/shuttles/common_vulture.dmm
Labels: Area : Mapping

#1040 Clothing Port + Minor Loadout fixes
  code/modules/client/loadout/neck.dm
  code/modules/client/loadout/suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/horizon/obj/clothing/suits.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Area : Sprites, Type : Fix

#1039 Touches up the ESS Crow
  _maps/shuttles/exploration_crow.dmm
  code/modules/shuttle/sold_shuttles.dm
Labels: Area : Mapping

#1057 Adds LRHPs to techwebs and circuit imprinters
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Type : Quality of Life, Area : Gameplay

#1071 Insulated gloves no longer give you chunky fingers
  code/modules/clothing/gloves/color.dm
Labels: Area : Balance, Area : Gameplay

#1070 Fixes foodtypes and removes some GROSS flags
  code/datums/materials/meat.dm
  code/datums/materials/pizza.dm
  code/game/objects/items/food/burgers.dm
  code/game/objects/items/food/meat.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/kudzu.dm
Labels: Type : Fix, Area : Gameplay

#1076 Cargo Pack QoL & Additions (Boombox Goodie, RCD, meat/pizza re-jiggery)
  code/modules/cargo/goodies.dm
  code/modules/cargo/packs.dm
Labels: Type : Balance, Type : Quality of Life, Area : Gameplay

#1082 Little code style refactor for species
  code/__DEFINES/customization/DNA.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/akula.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/aquatic.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/humanoid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/insect.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mammal.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/robotic.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
  code/modules/mob/living/carbon/human/species_types/snail.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/tajaran.dm
  code/modules/mob/living/carbon/human/species_types/teshari.dm
  code/modules/mob/living/carbon/human/species_types/unathi.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Type : Refactor

#1084 Remove temperature pumps
  code/game/objects/items/RPD.dm
  code/modules/atmospherics/machinery/components/binary_devices/temperature_pump.dm
  tgstation.dme
Labels: Type : Removal, Area : Gameplay

#1086 🚀 Converted pride week into pride month 🏳️‍🌈
  code/__DEFINES/colors.dm
  code/__DEFINES/time.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/modules/holiday/holidays.dm
Labels: Type : Refactor, Type : Feature

#1073 New dresses to Clothesmate & Cargo
  code/modules/cargo/packs.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/vending/clothesmate.dm
Labels: Area : Sprites

#1077 ERT Medic loadout changes
  code/modules/clothing/outfits/ert.dm
Labels: Area : Administration, Type : Balance

#1089 Energy Gun Visual Update!
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/gamemodes/objective_items.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/trading/sold_goods/weaponry.dm
  icons/obj/guns/energy.dmi
Labels: Area : Sprites, Type : Balance

#1091 Fixes mix messages when making multiple reagents
  code/modules/reagents/chemistry/holder.dm
Labels: Type : Fix, Area : Gameplay

#1102 Removed magical trauma resilience
  code/__DEFINES/mobs.dm
  code/game/machinery/medical_kiosk.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/events/brain_trauma.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/advanced/lobotomy.dm
Labels: Type : Balance, Type : Removal, Area : Gameplay

#1105 Adds the Suspected Icon to sechuds/warrant computers.
  code/game/data_huds.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hud.dmi
Labels: Area : Sprites

#1090 Increased spawned planets to three; map content config list refactor
  code/datums/map_config.dm
  code/modules/map_content/deltastation_define.dm
  code/modules/map_content/icebox_define.dm
  code/modules/map_content/kilostation_define.dm
  code/modules/map_content/metastation_define.dm
  code/modules/map_content/multiz_debug_define.dm
  code/modules/map_content/pubbystation_define.dm
  code/modules/map_content/runtimestation_define.dm
  code/modules/map_content/tradership/tradership_define.dm
  code/modules/map_content/tramstation_define.dm
Labels: Type : Refactor, Type : Balance

#1052 Kilo Station QoL Changes and Freight Dock Bridge
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Area : Mapping, Type : Balance, Type : Removal, Type : Quality of Life

#1120 Make perfumes last three times as long (30 minutes)
  code/modules/pollution/perfumes.dm
Labels: Type : Quality of Life, Area : Gameplay

#1122 Reduce arcade game noises, slightly increase modular computer noises
  code/datums/looping_sounds/machinery_sounds.dm
  code/modules/modular_computers/file_system/programs/arcade.dm
Labels: Area : Sounds, Type : Quality of Life

#1115 Megafauna will no longer devour (gib) dead targets
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Type : Balance, Area : Gameplay

#1067 Cypress's Icebox Changes
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: Area : Mapping, Type : Fix, Type : Quality of Life

#1106 Adds the CTS Pigeon and EMS Rockdove
  _maps/shuttles/common_pigeon.dmm
  _maps/shuttles/common_rockdove.dmm
  code/game/area/areas/shuttles.dm
  code/modules/shuttle/common_docks.dm
  code/modules/shuttle/sold_shuttles.dm
Labels: Area : Mapping

#1126 Icebox Fixes (plumb/wire/heatpump errors)
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
Labels: Area : Mapping, Type : Fix

#1116 New Laser Gun Sprites! (Plus one extra energy gun variant sprite)
  code/modules/projectiles/guns/energy/laser.dm
  icons/obj/guns/energy.dmi
Labels: Area : Sprites

#1128 Unifies abstract types
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/Mining/Lavaland.dmm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/processing/instruments.dm
  code/datums/datum.dm
  code/game/atoms.dm
  code/game/objects/structures/statues.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/explorer_drone/exploration_events/_exploration_event.dm
  code/modules/explorer_drone/exploration_events/adventure.dm
  code/modules/explorer_drone/exploration_events/danger.dm
  code/modules/explorer_drone/exploration_events/resource.dm
  code/modules/explorer_drone/exploration_events/trader.dm
  code/modules/explorer_drone/exploration_site.dm
  code/modules/instruments/instrument_data/_instrument_data.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Area : Mapping, Type : Refactor, Type : Removal

#1127 Adds Sensors to tacticool turtleneck/skirtleneck
  code/modules/clothing/under/syndicate.dm
Labels: Type : Quality of Life, Area : Gameplay

#1069 Slapcraft Framework
  code/__DEFINES/slapcraft.dm
  code/_globalvars/slapcraft.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/slapcraft/base_steps/slapcraft_step_reagent.dm
  code/modules/slapcraft/base_steps/slapcraft_step_reagent_container.dm
  code/modules/slapcraft/base_steps/slapcraft_step_stack.dm
  code/modules/slapcraft/base_steps/slapcraft_step_tool.dm
  code/modules/slapcraft/base_steps/slapcraft_step_weapon.dm
  code/modules/slapcraft/living_slapcraft.dm
  code/modules/slapcraft/recipes/weapons/flamethrower.dm
  code/modules/slapcraft/recipes/weapons/ied.dm
  code/modules/slapcraft/slapcraft_assembly.dm
  code/modules/slapcraft/slapcraft_handbook.dm
  code/modules/slapcraft/slapcraft_recipe.dm
  code/modules/slapcraft/slapcraft_step.dm
  icons/hud/screen_clockwork.dmi
  icons/hud/screen_glass.dmi
  icons/hud/screen_midnight.dmi
  icons/hud/screen_plasmafire.dmi
  icons/hud/screen_retro.dmi
  icons/hud/screen_slimecore.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Removal, Type : Feature

#1130 Overfed examine and slowdown changes
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/movespeed/modifiers/mobs.dm
Labels: Type : Balance, Area : Grammar and Formatting

#1083 Set the icon_render_key to null when applying character preferences
  code/modules/client/preferences.dm
Labels: Area : Sprites, Type : Fix

#1020 Added the bathrobe
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/clothing/under/misc.dmi
  icons/obj/clothing/under/misc.dmi
Labels: Area : Sprites

#1050 AI OC holograms
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Type : Feature, Area : Gameplay

#1138 Fixed ghost floating and orbiting animations
  code/__DEFINES/traits.dm
  code/datums/components/orbiter.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Type : Fix

#1139 Patched security issue in locate() wrapper
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: Type : Port, Area : Administration

#1065 Hologram Emotes and RUNEchat
  code/game/machinery/hologram.dm
Labels: Type : Quality of Life, Area : Gameplay

#1141 Makes TTS device cheaper in loadout + loadout suspenders!
  code/modules/client/loadout/backpack.dm
  code/modules/client/loadout/suit.dm
Labels: Type : Balance, Type : Quality of Life

#1142 Fixes bad points comparison on loadout validation
  code/modules/client/preferences_loadout.dm
Labels: Type : Fix

#1143 Fixes Storyteller pop scalling bug
  code/controllers/subsystem/gamemode.dm
Labels: Type : Fix, Area : Gameplay

#1149 Changes Techweb Program Access Requirement
  code/modules/modular_computers/file_system/programs/techweb.dm
Labels: Type : Balance, Area : Gameplay

#1147 Adds bloom overlays
  code/__DEFINES/layers.dm
  code/_globalvars/bloom.dm
  code/_onclick/hud/plane_master.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/structures/fireplace.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/power/floodlight.dm
  code/modules/power/lighting.dm
  icons/effects/bloom/bloom_large.dmi
  icons/effects/bloom/bloom_medium.dmi
  icons/effects/bloom/bloom_small.dmi
  tgstation.dme
Labels: Area : Sprites, Type : Feature

#1137 Recipe Framework
  code/__DEFINES/recipe.dm
  code/__HELPERS/cmp.dm
  code/_globalvars/recipe.dm
  code/modules/recipe/base_components/recipe_component_item.dm
  code/modules/recipe/base_components/recipe_component_reagent.dm
  code/modules/recipe/base_components/recipe_component_stack.dm
  code/modules/recipe/base_results/recipe_result_item.dm
  code/modules/recipe/perform_recipes.dm
  code/modules/recipe/recipe.dm
  code/modules/recipe/recipe_component.dm
  code/modules/recipe/recipe_component_state.dm
  code/modules/recipe/recipe_result.dm
  tgstation.dme
Labels: Type : Feature

#1148 Storyteller tweaks
  code/__DEFINES/storyteller.dm
  code/game/gamemodes/storytellers/various.dm
  config/game_options.txt
Labels: Area : Configuration, ⚠️ Warn : Config Update, Type : Balance

#1146 Removed overmap ability from laborcamp shuttles
  code/modules/mining/laborcamp/laborshuttle.dm
Labels: Type : Fix

#1145 Added reapply-prefs VV dropdown option
  code/__DEFINES/vv.dm
  code/modules/mob/mob.dm
Labels: Area : Administration, Type : Quality of Life

#1096 Fix: Cutting Cable colors
  code/modules/power/cable.dm
Labels: Type : Fix, Area : Gameplay

#1140 Refactored roundend sfx w/ flist(), removed five sounds, added one
  code/controllers/subsystem/ticker.dm
  sound/roundend/apcdestroyed.ogg
  sound/roundend/connection_terminated.ogg
  sound/roundend/disappointed.ogg
  sound/roundend/leavingtg.ogg
  sound/roundend/petersondisappointed.ogg
  sound/roundend/yeehaw.ogg
Labels: Area : Sounds, Type : Quality of Life

#1153 New chopping wood method (slapcraft edition)
  code/modules/hydroponics/grown/towercap.dm
  code/modules/slapcraft/recipes/misc/chop_log.dm
  tgstation.dme
Labels: Type : Refactor, Area : Gameplay

#1158 Fixed item drop animation resetting transforms
  code/game/objects/items.dm
Labels: Type : Fix

#1159 Ambient SFX additions, adjustments (general, vending machine, AI spacejam)
  code/__DEFINES/ambient_sounds.dm
  code/game/area/areas/ruins/space.dm
  code/game/area/space_station_13_areas.dm
  code/modules/ambience/ambient_sounds/ambient_sounds.dm
  sound/ambience/loudspeaker/intercom_deep1.ogg
  sound/ambience/loudspeaker/intercom_deep2.ogg
  sound/ambience/loudspeaker/intercom_deep3.ogg
  sound/ambience/loudspeaker/intercom_deep4.ogg
Labels: Area : Sounds

#1160 Removes power requirement from the drying rack
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Type : Quality of Life

#1131 Changed mail to also be delivered on Sundays
  code/controllers/subsystem/economy.dm
Labels: Type : Balance

#1162 Removed bluespace gas senders and vendors
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/atmospherics/machinery/bluespace_vendor.dm
  code/modules/atmospherics/machinery/components/unary_devices/bluespace_sender.dm
  icons/obj/atmospherics/components/bluespace_gas_selling.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/BluespaceSender.js
  tgui/packages/tgui/interfaces/BluespaceVendor.js
Labels: Area : Mapping, Area : UI/UX, Area : Sprites, Type : Removal, Area : Gameplay

#1164 Lowers bloom intensity
  code/_globalvars/bloom.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/power/lighting.dm
Labels: Type : Quality of Life

#1166 Revert "Hologram Emotes and RUNEchat"
  code/game/machinery/hologram.dm
Labels: Type : Removal

#1161 Ported airlock naming and cycling ID set up. Allows creating or repairing cycling airlocks ingame
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/structures/door_assembly.dm
  code/game/turfs/open/floor.dm
  tgui/packages/tgui/interfaces/AirlockElectronics.js
Labels: Type : Port, Area : UI/UX, Type : Feature, Area : Gameplay

#1167 Added Circuit Module Duplicator to Pubby Station
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Feature

#1168 Added Circuit Module Duplicator to icebox, kilo and tram
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Area : Mapping, Type : Feature

#1176 Removes Duplicate APC from the Rockdove
  _maps/shuttles/common_rockdove.dmm
Labels: Area : Mapping, Type : Fix

#1174 Icemoon Hermit Upkeep
  _maps/RandomRuins/IceRuins/icemoon_underground_hermit.dmm
  code/game/area/areas/ruins/icemoon.dm
Labels: Area : Mapping

#1172 Reduced range and volume of vending machine noises a tad
  code/modules/ambience/ambient_sounds/ambient_sounds.dm
Labels: Area : Sounds

#1135 Minor Kilo Station fixes
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Area : Mapping, Type : Fix

#1175 Limits Radstorms to Outside the Surface of Stations
  code/datums/weather/weather_types/radiation_storm.dm
Labels: Type : Balance

#1180 Added SPAN_INFOPLAIN macro, converted infoplain spans to it
  code/__DEFINES/span.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/vote.dm
  code/datums/helper_datums/getrev.dm
  code/datums/mind.dm
  code/datums/mutations/speech.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/deadmin_asay.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/assembly/health.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/who.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/mob.dm
  code/modules/photography/camera/silicon_camera.dm
Labels: Type : Refactor

#1171 Adds Silicon Players to crew manifest
  code/datums/datacore.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Area : UI/UX, Type : Feature, Area : Gameplay

#1169 Icebox Mining Base Rebuild
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Below.dmm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/area/areas/mining.dm
Labels: Area : Mapping

#1177 Milkshakes!
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  icons/obj/drinks.dmi
Labels: Area : Sprites

#1188 Removed xenoegg spawns from Pubby, fixed nanite room in Pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Removal

#1186 Medical Sprite Update Part 1
  code/modules/client/loadout/suit.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/bodybag.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/defib.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/syringe.dmi
Labels: Area : Sprites

#1189 Ports Tau Ceti welding effect
  code/game/objects/items.dm
  code/game/objects/items/tools/weldingtool.dm
  icons/effects/welding_effect.dmi
Labels: Area : Sprites

#1192 Virology Low-pop access update
  code/datums/id_trim/jobs.dm
Labels: Type : Balance

#1193 Silicons now added to manifest at round start
  code/datums/datacore.dm
Labels: Type : Fix, Area : Gameplay

#1185 Pubby Service QoL/Balance & Fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Area : Mapping, Type : Fix, Type : Balance, Type : Quality of Life

#1187 Icebox Mining Base: Area Fixes & Clarke => Ripley Downgrade
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Below.dmm
  code/game/area/areas/mining.dm
Labels: Area : Mapping, Type : Fix, Type : Balance

#1178 Ports the /tg/ drink-desouling update & new recipes
  code/game/objects/effects/contraband.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  icons/horizon/obj/drinks.dmi
  icons/obj/contraband.dmi
  icons/obj/drinks.dmi
  icons/obj/janitor.dmi
  icons/obj/vending.dmi
Labels: Type : Port, Area : Sprites, Type : Feature
