Repository hrzntal/horizon, pull requests merged in 2022-02, with the labels that each got.

#733 Update changelog generators
  .github/workflows/changelog_daily_compile.yml
  .github/workflows/changelog_pr_ingest.yml
  .github/workflows/changelog_pr_validate.yml
  .github/workflows/ci_suite.yml
  .github/workflows/compile_changelogs.yml
  html/changelogs/__CHANGELOG_README.txt
  html/changelogs/example.yml
  tools/changelogs/LICENSE
  tools/changelogs/README.md
  tools/changelogs/compile_monthly_changelogs.py
  tools/changelogs/config.json
  tools/changelogs/config.schema.json
  tools/changelogs/ingest_pr_changelog.py
  tools/changelogs/requirements.txt
  tools/changelogs/type_definitions.json
  tools/changelogs/type_definitions.schema.json
  tools/ci/check_changelogs.sh
  tools/ss13_genchangelog.py
Labels: Area : Tools, Area : Repository

#827 Changelog workflow fixup
  .github/workflows/changelog_daily_compile.yml
  .github/workflows/changelog_pr_ingest.yml
Labels: Area : Repository, Type : Fix

#743 Game options only available after init
  code/controllers/master.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Area : UI/UX, Type : Fix

#829 More changelog backend fixes
  .github/workflows/changelog_daily_compile.yml
  .github/workflows/changelog_pr_ingest.yml
  html/changelogs/auto-pr-changelog-743.yml
Labels: Area : Repository, Type : Fix

#745 Fixes double beds icon and refactors code
  code/game/objects/structures/beds_chairs/bed.dm
  icons/obj/objects.dmi
Labels: Area : Sprites, Type : Fix, Type : Refactor

#746 Clarifies catwalk stack usage
  code/game/objects/items/stacks/catwalk.dm
Labels: Area : Grammar and Formatting

#749 Fixes accessories not getting offsets, improves clothing render code
  code/__DEFINES/mobs.dm
  code/modules/clothing/under/_under.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/teshari.dm
Labels: Area : Sprites, Type : Fix

#750 Better door auto align
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/poddoor.dm
Labels: Type : Fix, Type : Refactor

#751 Sanitize ahelp communication
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Area : Administration, Severity : I

#752 Fixes space heater attack chain
  code/game/machinery/spaceheater.dm
Labels: Type : Fix

#753 Fixes missing icon state for suit storage cig pack
  icons/mob/clothing/belt_mirror.dmi
Labels: Area : Sprites

#754 Fixes check power cable debug layers
  code/modules/admin/verbs/atmosdebug.dm
Labels: Type : Fix, Area : Administration

#759 Changing a turf no longer disintegrates lattices
  code/game/turfs/change_turf.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
Labels: Type : Fix

#761 More carbon interactions
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  sound/effects/nose_boop.ogg
Labels: Area : Sounds, Area : Gameplay

#756 deer tail, ears, antlers and dual color neck fluff
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/neck.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  icons/mob/sprite_accessory/ears.dmi
  icons/mob/sprite_accessory/horns_big.dmi
  icons/mob/sprite_accessory/moth_fluff.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Area : Sprites

#762 Item Pickup Brush-Up #64095
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
Labels: Type : Mirror, Type : Fix, Type : Feature

#764 Fixes multi-z and other pulling/buckling behaviours
  code/__DEFINES/misc.dm
  code/datums/industrial_lift/lift_controller.dm
  code/datums/map_zones.dm
  code/game/atoms_movable.dm
  code/game/objects/structures/industrial_lift.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
Labels: Type : Fix

#765 Gives a bunch of table sized and/or shaped things LETPASSTHROW #63964
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/plumbing/plumbers/_plumb_machinery.dm
  code/modules/plumbing/plumbers/destroyer.dm
  code/modules/plumbing/plumbers/plumbing_buffer.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/religion/religion_structures.dm
Labels: Type : Feature

#766 Fixes ambient occlusion preference
  code/_onclick/hud/plane_master.dm
  code/modules/client/preferences.dm
Labels: Type : Fix

#769 Refactors ripley cargo code and adds feedback
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Type : Refactor, Type : Quality of Life

#776 Revert "Removes telegraph messages from weather"
  code/datums/weather/weather.dm
Labels: Area : UI/UX

#777 Obstructed low walls cant be deleted through explosions
  code/game/objects/structures/low_wall.dm
Labels: Type : Fix

#780 Liberator's Synthanol
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
Labels: Area : Sprites, Type : Feature

#781 Fixes crashing into obstructed openspace
  code/modules/mob/living/living.dm
Labels: Type : Fix

#782 Removes RCD interactions from concrete walls
  code/game/turfs/closed/wall/misc_walls.dm
Labels: Type : Fix

#784 Ensures that COMSIG_PARENT_QDELETING is sent before client Destroy.
  code/modules/client/client_procs.dm
Labels: Type : Mirror, Type : Fix

#786 Cryopod fixes and improvements
  code/game/machinery/cryopod.dm
Labels: Type : Fix, Type : Quality of Life

#788 Emergency Pod bandaid fix
  code/modules/shuttle/emergency.dm
Labels: Type : Fix

#793 Fixes planet atmosphere gas string generation
  code/datums/atmosphere/_atmosphere.dm
Labels: Type : Fix

#803 All purchasable shuttles now have a stock of 2
  code/modules/shuttle/sold_shuttles.dm
Labels: Type : Quality of Life

#794 Adds desert planet to habitable planets spawn pool
  code/__DEFINES/overmap.dm
Labels: Type : Quality of Life

#817 Fixes railing corner sprites
  icons/obj/fluff.dmi
Labels: Area : Sprites

#808 Sets a better plastitanium wall color
  code/datums/materials/alloys.dm
Labels: Type : Quality of Life

#804 Re-adds hardsuits and spacesuits to cargo packs
  code/modules/cargo/packs.dm
Labels: Type : Quality of Life

#813 Adds Kinetic Crusher to Mining borgs
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Type : Feature

#814 Refactors Kinetic Accelerator Upgrades
  code/datums/status_effects/neutral.dm
  code/game/objects/structures/icemoon/cave_entrance.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/research/designs/mining_designs.dm
  code/modules/uplink/uplink_items.dm
Labels: Type : Refactor, Type : Feature

#820 Fixes NTOS Chat client Bluescreen when in admin mode
  tgui/packages/tgui/interfaces/NtosNetChat.js
Labels: Area : UI/UX, Type : Fix

#821 Moves spans from TTS description to it's examine
  code/game/objects/items/devices/ttsdevice.dm
Labels: Type : Fix

#815 Ports reinforced glass tables from TG#61153
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/smooth_structures/plasmaglass_table.dmi
  icons/obj/smooth_structures/plastitaniumglass_table.dmi
  icons/obj/smooth_structures/rglass_table.dmi
  icons/obj/smooth_structures/rplasmaglass_table.dmi
  icons/obj/smooth_structures/titaniumglass_table.dmi
Labels: Type : Mirror, Area : Sprites

#767 Offsets directional lights to fit onto our walls
  code/modules/power/lighting.dm
Labels: Type : Quality of Life

#802 Welding Fizz and Lubricola, casual drinks for robots
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/vending/cola.dm
  icons/obj/drinks.dmi
Labels: Area : Sprites, Type : Feature

#831 Renovates Space Hotel
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  code/game/area/areas/ruins/space.dm
  code/modules/mapping/mapping_helpers/paint_wall_helper.dm
Labels: Area : Mapping

#838 Removes gibbing from Heretic Sacrifices
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
Labels: Area : Balance, Type : Quality of Life, Area : Gameplay

#847 Hyena Emotes and accompanied SFX
  code/modules/mob/living/emote.dm
  sound/voice/hyena/cackle.ogg
  sound/voice/hyena/cackle_giggle.ogg
  sound/voice/hyena/laugh1.ogg
  sound/voice/hyena/laugh2.ogg
  sound/voice/hyena/laugh_bright.ogg
  sound/voice/hyena/laugh_low.ogg
  sound/voice/hyena/laugh_short.ogg
  sound/voice/hyena/laugh_twice.ogg
  sound/voice/hyena/license.md
  sound/voice/hyena/whoop.ogg
  sound/voice/hyena/whoop_long.ogg
Labels: Area : Sounds, Type : Feature
