Repository hrzntal/horizon, pull requests merged in 2022-04, with the labels that each got.

#853 Fixes admin only suffix for deadchat broadcast messages
  code/__HELPERS/mobs.dm
Labels: Type : Fix

#852 Panic Bunker: Discord Requirement
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/discord_helpers.dm
  code/modules/discord/discord_link_record.dm
  code/modules/discord/discord_sql_functions.dm
  code/modules/discord/tgs_commands.dm
  code/modules/discord/toggle_notify.dm
  config/config.txt
  strings/eff_large_wordlist.txt
  tgstation.dme
Labels: Area : Configuration, Warn : Config Update, Area : Administration, Type : Feature

#856 Fixes two overflow pixels on the male digitigrade chest
  icons/mob/species/mammal_parts_greyscale.dmi
Labels: Area : Sprites, Type : Fix

#858 Discordlink bugfixes
  code/modules/client/client_procs.dm
  code/modules/discord/discord_helpers.dm
Labels: Type : Fix

#861 Fixes gravity generator turning itself off while already off
  code/modules/power/gravitygenerator.dm
Labels: Type : Fix
